var filmes = [
    {"numFilme": 1, "nomePT": "Viagem Á Lua", "nomeOriginal": "Le Voyage Dans La Lune"}, 
    {"numFilme": 2, "nomePT": "O Grande Roubo Do Trem", "nomeOriginal": "The Great Train Robbery"}, 
    {"numFilme": 3, "nomePT": "O Nascimento De Uma Nação", "nomeOriginal": "The Birth Os A Nation"}, 
    {"numFilme": 4, "nomePT": "Os Vampiros", "nomeOriginal": "Les Vampires"}, 
    {"numFilme": 5, "nomePT": "Intolerância", "nomeOriginal": "Intolerance"}, 
    {"numFilme": 6, "nomePT": "O Gabinete Do Dr. Caligari", "nomeOriginal": "Das Kabinett Des Doktor Caligari"}, 
    {"numFilme": 7, "nomePT": "Lírio Partido", "nomeOriginal": "Broken Blossoms"}, 
    {"numFilme": 8, "nomePT": "Inocente Pecadora", "nomeOriginal": "Way Down East"}, 
    {"numFilme": 9, "nomePT": "Within Our Gates"}, 
    {"numFilme": 10, "nomePT": "A Carruagem Fantasma", "nomeOriginal": "Körkarlen"}, 
    {"numFilme": 11, "nomePT": "Órfãos Da Tempestade", "nomeOriginal": "Orphans Of The Storm"}, 
    {"numFilme": 12, "nomePT": "A Sorridente Madame Beudet", "nomeOriginal": "La Souriante Madame Beudet"}, 
    {"numFilme": 13, "nomePT": "Dr. Mabuse", "nomeOriginal": "Dr. Mabuse, Der Spieler"}, 
    {"numFilme": 14, "nomePT": "Nanook, O Esquimó", "nomeOriginal": "Nannok Of The North"}, 
    {"numFilme": 15, "nomePT": "Nosferatu, Uma Sinfonia De Horror", "nomeOriginal": "Nosferatu, Eine Symphonie Des Grauens"}, 
    {"numFilme": 16, "nomePT": "Esposas Ingênuas", "nomeOriginal": "Foolish Wives"}, 
    {"numFilme": 17, "nomePT": "Häxan - A Feitiçaria Através Dos Tempos", "nomeOriginal": "Häxan"}, 
    {"numFilme": 18, "nomePT": "Nossa Hospitalidade", "nomeOriginal": "Our Hospitality"}, 
    {"numFilme": 19, "nomePT": "A Roda", "nomeOriginal": "La Roue"}, 
    {"numFilme": 20, "nomePT": "O Ladrão De Bagdá", "nomeOriginal": "The Thief Of Bagdad"}, 
    {"numFilme": 21, "nomePT": "A Greve", "nomeOriginal": "Stachka"}, 
    {"numFilme": 22, "nomePT": "Ouro E Maldição", "nomeOriginal": "Greed"}, 
    {"numFilme": 23, "nomePT": "Sherlock Jr."}, 
    {"numFilme": 24, "nomePT": "A Última Gargalhada", "nomeOriginal": "Der Letzte Mann"}, 
    {"numFilme": 25, "nomePT": "Sete Oportunidades", "nomeOriginal": "Seven Chances"}, 
    {"numFilme": 26, "nomePT": "O Fantasma Da Ópera", "nomeOriginal": "The Phantom Of The Opera"}, 
    {"numFilme": 27, "nomePT": "O Encouraçado Potemkin", "nomeOriginal": "Bronenosets Potyomkin"}, 
    {"numFilme": 28, "nomePT": "Em Busca Do Ouro", "nomeOriginal": "The Gold Rush"}, 
    {"numFilme": 29, "nomePT": "O Grande Desfile", "nomeOriginal": "The Big Parade"}, 
    {"numFilme": 30, "nomePT": "Metrópolis", "nomeOriginal": "Metropolis"}, 
    {"numFilme": 31, "nomePT": "Aurora", "nomeOriginal": "Sunrise"}, 
    {"numFilme": 32, "nomePT": "A General", "nomeOriginal": "The General"}, 
    {"numFilme": 33, "nomePT": "O Monstro Do Circo", "nomeOriginal": "The Unknown"}, 
    {"numFilme": 34, "nomePT": "Outubro", "nomeOriginal": "Oktyabr"}, 
    {"numFilme": 35, "nomePT": "O Cantor De Jazz", "nomeOriginal": "The Jazz Singer"}, 
    {"numFilme": 36, "nomePT": "Napoleão", "nomeOriginal": "Napoléon"}, 
    {"numFilme": 37, "nomePT": "O Caçula", "nomeOriginal": "The Kid Brother"}, 
    {"numFilme": 38, "nomePT": "A Turba", "nomeOriginal": "The Crowd"}, 
    {"numFilme": 39, "nomePT": "Docas De Nova York", "nomeOriginal": "The Docks Of New York"}, 
    {"numFilme": 40, "nomePT": "Um Cão Andaluz", "nomeOriginal": "Um Chien Andalou"}, 
    {"numFilme": 41, "nomePT": "A Paixão De Joana D’Arc", "nomeOriginal": "La Passion De Jeanne D’Arc"}, 
    {"numFilme": 42, "nomePT": "Capitão Bill Jr.", "nomeOriginal": "Steamboat Bill, Jr."}, 
    {"numFilme": 43, "nomePT": "Tempestade Sobre A Ásia", "nomeOriginal": "Potomok Chingis-Khana"}, 
    {"numFilme": 44, "nomePT": "Chantagem E Confissão", "nomeOriginal": "Blackmail"}, 
    {"numFilme": 45, "nomePT": "Um Homem Com Uma Câmera", "nomeOriginal": "Chelovek’s Kinoapparatom"}, 
    {"numFilme": 46, "nomePT": "A Caixa De Pandora", "nomeOriginal": "Die Büchse Der Pandora"}, 
    {"numFilme": 47, "nomePT": "O Anjo Azul", "nomeOriginal": "Der Blaue Engel"}, 
    {"numFilme": 48, "nomePT": "A Idade Do Ouro", "nomeOriginal": "L’Âge D’Or"}, 
    {"numFilme": 49, "nomePT": "Terra", "nomeOriginal": "Zemlya"}, 
    {"numFilme": 50, "nomePT": "Alma No Lodo", "nomeOriginal": "Little Caesar"}, 
    {"numFilme": 51, "nomePT": "Sem Novidades No Front", "nomeOriginal": "All Quiet On The Western Front"}, 
    {"numFilme": 52, "nomePT": "A Nós A Liberdade", "nomeOriginal": "À Nous La Liberté"}, 
    {"numFilme": 53, "nomePT": "O Milhão", "nomeOriginal": "Le Million"}, 
    {"numFilme": 54, "nomePT": "Limite"}, 
    {"numFilme": 55, "nomePT": "Drácula", "nomeOriginal": "Dracula"}, 
    {"numFilme": 56, "nomePT": "Frankenstein"}, 
    {"numFilme": 57, "nomePT": "Luzes Da Cidade", "nomeOriginal": "City Lights"}, 
    {"numFilme": 58, "nomePT": "O Inimigo Público", "nomeOriginal": "The Public Enemy"}, 
    {"numFilme": 59, "nomePT": "M, O Vampiro De Dusseldorf", "nomeOriginal": "M"}, 
    {"numFilme": 60, "nomePT": "A Cadela", "nomeOriginal": "La Chienne"}, 
    {"numFilme": 61, "nomePT": "O Vampiro", "nomeOriginal": "Vampyr"}, 
    {"numFilme": 62, "nomePT": "Ama-me Esta Noite", "nomeOriginal": "love Me Tonight"}, 
    {"numFilme": 63, "nomePT": "Boudu Salvo das Águas", "nomeOriginal": "Boudu Sauvé Des Eaux"}, 
    {"numFilme": 64, "nomePT": "O Fugitivo", "nomeOriginal": "I Am A Fugitive From Chain Gang"}, 
    {"numFilme": 65, "nomePT": "Ladrão De Alcova", "nomeOriginal": "Trouble In Paradise"}, 
    {"numFilme": 66, "nomePT": "Scarface :  A Vergonha De Uma Nação", "nomeOriginal": "Scarface :  The Shame Of A Nation"}, 
    {"numFilme": 67, "nomePT": "O Expresso De Xangai", "nomeOriginal": "Shanghai Express"}, 
    {"numFilme": 68, "nomePT": "Monstros", "nomeOriginal": "Freaks"}, 
    {"numFilme": 69, "nomePT": "Eu E Minha Pequena", "nomeOriginal": "Me And My Gal"}, 
    {"numFilme": 70, "nomePT": "Zero De Conduta", "nomeOriginal": "Zéro De Conduite"}, 
    {"numFilme": 71, "nomePT": "Rua 42", "nomeOriginal": "42° Street"}, 
    {"numFilme": 72, "nomePT": "Belezas Em Revista", "nomeOriginal": "Footlight Parade"}, 
    {"numFilme": 73, "nomePT": "Caçadoras De Ouro", "nomeOriginal": "Gold Diggers Of"}, 
    {"numFilme": 74, "nomePT": "Uma Loira Para Três", "nomeOriginal": "She Done Him Wrong"}, 
    {"numFilme": 75, "nomePT": "Diabo A Quatro", "nomeOriginal": "Duck Soup"}, 
    {"numFilme": 76, "nomePT": "Rainha Cristina", "nomeOriginal": "Queen Christina"}, 
    {"numFilme": 77, "nomePT": "Terra Sem Pão", "nomeOriginal": "Las Hurdes"}, 
    {"numFilme": 78, "nomePT": "King Kong"}, 
    {"numFilme": 79, "nomePT": "O Último Chá Do General Yen", "nomeOriginal": "The Bitter Tea Of General Yen"}, 
    {"numFilme": 80, "nomePT": "Os Filhos Do Deserto", "nomeOriginal": "Sons Of The Desert"}, 
    {"numFilme": 81, "nomePT": "It’s A Gift"}, 
    {"numFilme": 82, "nomePT": "O Triunfo Da Vontade", "nomeOriginal": "Triumph Des Willens"}, 
    {"numFilme": 83, "nomePT": "O Atalante", "nomeOriginal": "L’Atalante"}, 
    {"numFilme": 84, "nomePT": "O Gato Preto", "nomeOriginal": "The Black Cat"}, 
    {"numFilme": 85, "nomePT": "O Juiz Priest", "nomeOriginal": "Judge Priest"}, 
    {"numFilme": 86, "nomePT": "Aconteceu Naquela Noite", "nomeOriginal": "It Happened One Night"}, 
    {"numFilme": 87, "nomePT": "A Ceia Dos Acusados", "nomeOriginal": "The Thin Man"}, 
    {"numFilme": 88, "nomePT": "Capitão Blood", "nomeOriginal": "Captain Blood"}, 
    {"numFilme": 89, "nomePT": "O Grande Motim", "nomeOriginal": "Mutiny On The Bounty"}, 
    {"numFilme": 90, "nomePT": "Uma Noite Na Ópera", "nomeOriginal": "A Night At The Opera"}, 
    {"numFilme": 91, "nomePT": "Os 39 Degraus", "nomeOriginal": "The 39 Steps"}, 
    {"numFilme": 92, "nomePT": "A Noiva De Frankenstein", "nomeOriginal": "Bride Of Frankenstein"}, 
    {"numFilme": 93, "nomePT": "O Picolino", "nomeOriginal": "Top Hat"}, 
    {"numFilme": 94, "nomePT": "Um Dia No Campo", "nomeOriginal": "Une Partie De Campagne"}, 
    {"numFilme": 95, "nomePT": "Tempos Modernos", "nomeOriginal": "Modern Times"}, 
    {"numFilme": 96, "nomePT": "Ritmo Louco", "nomeOriginal": "Swing Time"}, 
    {"numFilme": 97, "nomePT": "Irene A Teimosa", "nomeOriginal": "My Man Godfrey"}, 
    {"numFilme": 98, "nomePT": "O Galante Mr. Deeds", "nomeOriginal": "Mr. Deeds Goes To Town"}, 
    {"numFilme": 99, "nomePT": "A Dama Das Camélias", "nomeOriginal": "Camille"}, 
    {"numFilme": 100, "nomePT": "Sabotagem", "nomeOriginal": "Sabotage"}, 
    {"numFilme": 101, "nomePT": "Fogo de Outono", "nomeOriginal": "Dodsworth"}, 
    {"numFilme": 102, "nomePT": "Daqui A Cem Anos", "nomeOriginal": "Things To Come"}, 
    {"numFilme": 103, "nomePT": "A História De Um Trapaceiro", "nomeOriginal": "Le Roman D’Un Tricheur"}, 
    {"numFilme": 104, "nomePT": "Marujo Intrépido", "nomeOriginal": "Captains Courageous"}, 
    {"numFilme": 105, "nomePT": "Canção Da Noite", "nomeOriginal": "Yeaban Gesheng"}, 
    {"numFilme": 106, "nomePT": "A Grande Ilusão", "nomeOriginal": "La Grande Illusion"}, 
    {"numFilme": 107, "nomePT": "Stella Dallas, Mãe Redentora", "nomeOriginal": "Stella Dallas"}, 
    {"numFilme": 108, "nomePT": "A Vida De Émile Zola", "nomeOriginal": "The Life Of Emile Zola"}, 
    {"numFilme": 109, "nomePT": "A Cruz Dos Anos", "nomeOriginal": "Make Way For Tomorrow"}, 
    {"numFilme": 110, "nomePT": "Branca De Neve E Os Sete Anões", "nomeOriginal": "Snow White And The Seven Dwarves"}, 
    {"numFilme": 111, "nomePT": "Cupido É Moleque Teimoso", "nomeOriginal": "The Awful Truth"}, 
    {"numFilme": 112, "nomePT": "O Demônio Da Argélia", "nomeOriginal": "Pépé Le Moko"}, 
    {"numFilme": 113, "nomePT": "Jezebel"}, 
    {"numFilme": 114, "nomePT": "As Aventuras De Robin Hood", "nomeOriginal": "The Adventures Of Robin Hood"}, 
    {"numFilme": 115, "nomePT": "Anjos De Cara Suja", "nomeOriginal": "Angels With Dirty faces"}, 
    {"numFilme": 116, "nomePT": "Olympia"}, 
    {"numFilme": 117, "nomePT": "A Mulher Do Padeiro", "nomeOriginal": "La Femme Du Boulanger"}, 
    {"numFilme": 118, "nomePT": "Levada Da Breca", "nomeOriginal": "Bringing Up Baby"}, 
    {"numFilme": 119, "nomePT": "No Tempo Das Diligências", "nomeOriginal": "Stagecoach"}, 
    {"numFilme": 120, "nomePT": "Crisântemos Tardios", "nomeOriginal": "Zangiku Monogatari"}, 
    {"numFilme": 121, "nomePT": "Sangue De Artista", "nomeOriginal": "Babes In Arms"}, 
    {"numFilme": 122, "nomePT": "A Mulher Faz O Homem", "nomeOriginal": "Mr. Smith Goes To Washington"}, 
    {"numFilme": 123, "nomePT": "O Mágico De Oz", "nomeOriginal": "The Wizard Of Oz"}, 
    {"numFilme": 124, "nomePT": "Atire A Primeira Pedra", "nomeOriginal": "Destry Rides Again"}, 
    {"numFilme": 125, "nomePT": "Paraíso Infernal", "nomeOriginal": "Only Angels Have Wings"}, 
    {"numFilme": 126, "nomePT": "E O Vento Levou", "nomeOriginal": "Gone With The Wind"}, 
    {"numFilme": 127, "nomePT": "Trágico Amanhecer", "nomeOriginal": "Le Jour Se Lève"}, 
    {"numFilme": 128, "nomePT": "Gunga Din"}, 
    {"numFilme": 129, "nomePT": "Ninotchka"}, 
    {"numFilme": 130, "nomePT": "A Regra Do Jogo", "nomeOriginal": "La Règle Du Jeu"}, 
    {"numFilme": 131, "nomePT": "O Morro Dos Ventos Uivantes", "nomeOriginal": "Wuthering Heights"}, 
    {"numFilme": 132, "nomePT": "Jejum De Amor", "nomeOriginal": "His Girl Friday"}, 
    {"numFilme": 133, "nomePT": "Rebecca, A Mulher Inesquecível", "nomeOriginal": "Rebecca"}, 
    {"numFilme": 134, "nomePT": "Fantasia"}, 
    {"numFilme": 135, "nomePT": "Núpcias De Um Escândalo", "nomeOriginal": "The Philadelphia Story"}, 
    {"numFilme": 136, "nomePT": "As Vinhas Da Ira", "nomeOriginal": "The Grapes Of Wrath"}, 
    {"numFilme": 137, "nomePT": "A Vida É Uma Dança", "nomeOriginal": "Dance Girl Dance"}, 
    {"numFilme": 138, "nomePT": "Pinóquio", "nomeOriginal": "Pinocchio"}, 
    {"numFilme": 139, "nomePT": "Tempestades D’Alma", "nomeOriginal": "The Mortal Storm"}, 
    {"numFilme": 140, "nomePT": "O Guarda", "nomeOriginal": "The Bank Dick"}, 
    {"numFilme": 141, "nomePT": "Cidadão Kane", "nomeOriginal": "Citizen Kane"}, 
    {"numFilme": 142, "nomePT": "As Três Noites De Eva", "nomeOriginal": "The Lady Eve"}, 
    {"numFilme": 143, "nomePT": "O Lobisomem", "nomeOriginal": "The Wolf Man"}, 
    {"numFilme": 144, "nomePT": "O Falcão Maltês", "nomeOriginal": "The Maltese Falcon"}, 
    {"numFilme": 145, "nomePT": "Sargento York", "nomeOriginal": "Sargeant York"}, 
    {"numFilme": 146, "nomePT": "Dumbo"}, 
    {"numFilme": 147, "nomePT": "O Último Refúgio", "nomeOriginal": "High Sierra"}, 
    {"numFilme": 148, "nomePT": "Contrastes Humanos", "nomeOriginal": "Sullivan’s Travels"}, 
    {"numFilme": 149, "nomePT": "Como Era Verde Meu Vale", "nomeOriginal": "How Green Was My Valley"}, 
    {"numFilme": 150, "nomePT": "Mulher De Verdade", "nomeOriginal": "The Palm Beach Story"}, 
    {"numFilme": 151, "nomePT": "A Estranha Passageira", "nomeOriginal": "Now, Voyager"}, 
    {"numFilme": 152, "nomePT": "Casablanca"}, 
    {"numFilme": 153, "nomePT": "Ser Ou Não Ser", "nomeOriginal": "To Be Or Not To Be"}, 
    {"numFilme": 154, "nomePT": "A Marca Da Pantera", "nomeOriginal": "Cat People"}, 
    {"numFilme": 155, "nomePT": "Soberba", "nomeOriginal": "The Magnificent Ambersons"}, 
    {"numFilme": 156, "nomePT": "A Canção Da Vitória", "nomeOriginal": "Yankee Doodle Dandy"}, 
    {"numFilme": 157, "nomePT": "Meshes Of The Afternoon"}, 
    {"numFilme": 158, "nomePT": "Fires Were Started"}, 
    {"numFilme": 159, "nomePT": "The Man In Grey"}, 
    {"numFilme": 160, "nomePT": "Coronel Blimp - Vida E Morte", "nomeOriginal": "The Life And Death Of Colonel Blimp"}, 
    {"numFilme": 161, "nomePT": "A Morta Viva", "nomeOriginal": "I Walked With A Zombie"}, 
    {"numFilme": 162, "nomePT": "A Sétima Vítima", "nomeOriginal": "The Seventh Victim"}, 
    {"numFilme": 163, "nomePT": "Consciências Mortas", "nomeOriginal": "The Ox-Bow Incident"}, 
    {"numFilme": 164, "nomePT": "A Sombra De Uma Dúvida", "nomeOriginal": "Shadow Of A Doubt"}, 
    {"numFilme": 165, "nomePT": "Obsessão", "nomeOriginal": "Ossessione"}, 
    {"numFilme": 166, "nomePT": "Agora Seremos Felizes", "nomeOriginal": "Meet Me In St. Louis"}, 
    {"numFilme": 167, "nomePT": "Uma Aventura Na Martinica", "nomeOriginal": "To Have And Have Not"}, 
    {"numFilme": 168, "nomePT": "Laura"}, 
    {"numFilme": 169, "nomePT": "À Meia-Luz", "nomeOriginal": "Gaslight"}, 
    {"numFilme": 170, "nomePT": "Henrique V", "nomeOriginal": "Henry V"}, 
    {"numFilme": 171, "nomePT": "Ivan, O Terrível - Partes 1 e 2", "nomeOriginal": "Ivan Groznyj I and II"}, 
    {"numFilme": 172, "nomePT": "Pacto De Sangue", "nomeOriginal": "Double Indemnity"}, 
    {"numFilme": 173, "nomePT": "Até A Vista, Querida", "nomeOriginal": "Murder, My Sweet / Farewell My Lovely"}, 
    {"numFilme": 174, "nomePT": "A Batalha De San Pietro", "nomeOriginal": "The Battle Of San Pietro"}, 
    {"numFilme": 175, "nomePT": "Quando Fala O Coração", "nomeOriginal": "Spellbound"}, 
    {"numFilme": 176, "nomePT": "Alma Em Suplício", "nomeOriginal": "Mildred Pierce"}, 
    {"numFilme": 177, "nomePT": "O Boulevard Do Crime", "nomeOriginal": "Les Enfants Du Paradis"}, 
    {"numFilme": 178, "nomePT": "Roma, Cidade Aberta", "nomeOriginal": "Roma, Città Aperta"}, 
    {"numFilme": 179, "nomePT": "Farrapo Humano", "nomeOriginal": "The Lost Weekend"}, 
    {"numFilme": 180, "nomePT": "Curva Do Destino", "nomeOriginal": "Detour"}, 
    {"numFilme": 181, "nomePT": "Sei Onde Fica O Paraíso", "nomeOriginal": "I Know Where I’m Going"}, 
    {"numFilme": 182, "nomePT": "Os Melhores Anos De Nossa Vidas", "nomeOriginal": "The Best Years Of Our Lives"}, 
    {"numFilme": 183, "nomePT": "Desencanto", "nomeOriginal": "Brief Encounter"}, 
    {"numFilme": 184, "nomePT": "Paisá", "nomeOriginal": "Paisà"}, 
    {"numFilme": 185, "nomePT": "O Destino Bate Á Sua Porta", "nomeOriginal": "The Postman Always Rings Twice"}, 
    {"numFilme": 186, "nomePT": "Paixão De Fortes", "nomeOriginal": "My Darling Clementine"}, 
    {"numFilme": 187, "nomePT": "O Estranho", "nomeOriginal": "The Stranger"}, 
    {"numFilme": 188, "nomePT": "A Bela E A Fera", "nomeOriginal": "La Belle Et La Bête"}, 
    {"numFilme": 189, "nomePT": "A Beira Do Abismo", "nomeOriginal": "The Big Sleep"}, 
    {"numFilme": 190, "nomePT": "Os Assassinos", "nomeOriginal": "The Killers"}, 
    {"numFilme": 191, "nomePT": "Neste Mundo E No Outro", "nomeOriginal": "A Matter Of Life And Death"}, 
    {"numFilme": 192, "nomePT": "Grandes Esperanças", "nomeOriginal": "Graet Expectations"}, 
    {"numFilme": 193, "nomePT": "Interlúdio", "nomeOriginal": "Notorious"}, 
    {"numFilme": 194, "nomePT": "Narciso Negro", "nomeOriginal": "Black Narcisus"}, 
    {"numFilme": 195, "nomePT": "A Felicidade Não Se Compra", "nomeOriginal": "Its A Wondeful Life"}, 
    {"numFilme": 196, "nomePT": "Gilda"}, 
    {"numFilme": 197, "nomePT": "Monsieur Verdoux"}, 
    {"numFilme": 198, "nomePT": "Fuga Do Passado", "nomeOriginal": "Out Of The Past"}, 
    {"numFilme": 199, "nomePT": "O Fantasma Apaixonado", "nomeOriginal": "The Gost And Mrs. Muir"}, 
    {"numFilme": 200, "nomePT": "O Condenado", "nomeOriginal": "Odd Man Out"}, 
    {"numFilme": 201, "nomePT": "Ladrões De Bicicleta", "nomeOriginal": "Ladri Di Biciclette"}, 
    {"numFilme": 202, "nomePT": "Carta De Uma Desconhecida", "nomeOriginal": "Letter From An Unknown Woman"}, 
    {"numFilme": 203, "nomePT": "O Segredo Atrás Da Porta", "nomeOriginal": "Secret Beyond The Door"}, 
    {"numFilme": 204, "nomePT": "A Força Do Mal", "nomeOriginal": "Force Of Evil"}, 
    {"numFilme": 205, "nomePT": "Primavera Numa Pequena Cidade", "nomeOriginal": "Xiao Cheng Zhi Chun"}, 
    {"numFilme": 206, "nomePT": "Rio Vermelho", "nomeOriginal": "Red River"}, 
    {"numFilme": 207, "nomePT": "Festim Diabólico", "nomeOriginal": "Rope"}, 
    {"numFilme": 208, "nomePT": "Na Cova Da Serpente", "nomeOriginal": "The Snake Pit"}, 
    {"numFilme": 209, "nomePT": "A Dama De Shangai", "nomeOriginal": "The Lady From Shangai"}, 
    {"numFilme": 210, "nomePT": "O Valente Treme-Treme", "nomeOriginal": "The Paleface"}, 
    {"numFilme": 211, "nomePT": "Os Sapatinhos Vermelhos", "nomeOriginal": "The Red Shoes"}, 
    {"numFilme": 212, "nomePT": "O Tesouro De Sierra Madre", "nomeOriginal": "The Treasure Of Sierra Madre"}, 
    {"numFilme": 213, "nomePT": "A História De Louisina", "nomeOriginal": "Louisiana Story"}, 
    {"numFilme": 214, "nomePT": "Tarde Demais", "nomeOriginal": "The Heiress"}, 
    {"numFilme": 215, "nomePT": "As Oito Vítimas", "nomeOriginal": "Kind Hearts And Coronets"}, 
    {"numFilme": 216, "nomePT": "Mortalmente Perigosa", "nomeOriginal": "Gun Crazy / Deadly Is The Female"}, 
    {"numFilme": 217, "nomePT": "A Costela De Adão", "nomeOriginal": "The Adam’s Rib"}, 
    {"numFilme": 218, "nomePT": "Alegrias A Granel", "nomeOriginal": "Whisky Galore!"}, 
    {"numFilme": 219, "nomePT": "Fúria Sanguinária", "nomeOriginal": "White Heat"}, 
    {"numFilme": 220, "nomePT": "Na Teia Do Destino", "nomeOriginal": "The Reckless Moment"}, 
    {"numFilme": 221, "nomePT": "O Terceiro Homem", "nomeOriginal": "The Third Man"}, 
    {"numFilme": 222, "nomePT": "Um Dia Em Nova York", "nomeOriginal": "On the Town"}, 
    {"numFilme": 223, "nomePT": "Orfeu", "nomeOriginal": "Orphée"}, 
    {"numFilme": 224, "nomePT": "O Segredo Das Jóias", "nomeOriginal": "The Asphalt Jungle"}, 
    {"numFilme": 225, "nomePT": "Rashomon"}, 
    {"numFilme": 226, "nomePT": "Winchester ‘73"}, 
    {"numFilme": 227, "nomePT": "Rio Grande"}, 
    {"numFilme": 228, "nomePT": "A Malvada", "nomeOriginal": "All About Eve"}, 
    {"numFilme": 229, "nomePT": "Crepúsculo Dos Deuses", "nomeOriginal": "Sunset Boulevard"}, 
    {"numFilme": 230, "nomePT": "Os Esquecidos", "nomeOriginal": "Los Olvidados"}, 
    {"numFilme": 231, "nomePT": "No Silêncio Da Noite", "nomeOriginal": "In a Lonely Place"}, 
    {"numFilme": 232, "nomePT": "A Montanha Dos Sete Abutres", "nomeOriginal": "Ace In The Hole"}, 
    {"numFilme": 233, "nomePT": "Uma Rua Chamada Pecado", "nomeOriginal": "A Streetcar Named Desire"}, 
    {"numFilme": 234, "nomePT": "Pacto Sinistro", "nomeOriginal": "Strangers on a Train"}, 
    {"numFilme": 235, "nomePT": "O Mistério Da Torre", "nomeOriginal": "The Lavender Hill Mob"}, 
    {"numFilme": 236, "nomePT": "Os Amores De Pandora", "nomeOriginal": "Pandora and the Flying Dutchman"}, 
    {"numFilme": 237, "nomePT": "Uma Aventura Na África", "nomeOriginal": "The African Queen"}, 
    {"numFilme": 238, "nomePT": "Diário De Um Padre", "nomeOriginal": "Journal d’Un Curé de Campagne"}, 
    {"numFilme": 239, "nomePT": "Sinfonia De Paris", "nomeOriginal": "An American in Paris"}, 
    {"numFilme": 240, "nomePT": "Um Lugar Ao Sol", "nomeOriginal": "A Place in the Sun"}, 
    {"numFilme": 241, "nomePT": "O Dia Em Que A Terra Parou", "nomeOriginal": "The Day the Earth Stood Still"}, 
    {"numFilme": 242, "nomePT": "Depois Do Vendaval", "nomeOriginal": "The Quiet Man"}, 
    {"numFilme": 243, "nomePT": "Brinquedo Proibido", "nomeOriginal": "Jeux Interdits"}, 
    {"numFilme": 244, "nomePT": "Alma Em Pânico", "nomeOriginal": "Angel Face"}, 
    {"numFilme": 245, "nomePT": "Cantando Na Chuva", "nomeOriginal": "Singin’ in the Rain"}, 
    {"numFilme": 246, "nomePT": "Viver", "nomeOriginal": "Ikiru"}, 
    {"numFilme": 247, "nomePT": "Europa ‘51"}, 
    {"numFilme": 248, "nomePT": "Assim Estava Escrito", "nomeOriginal": "The Bad and the Beautiful"}, 
    {"numFilme": 249, "nomePT": "O Rio Da Aventura", "nomeOriginal": "The Big Sky"}, 
    {"numFilme": 250, "nomePT": "Matar Ou Morrer", "nomeOriginal": "High Noon"}, 
    {"numFilme": 251, "nomePT": "Umberto D"}, 
    {"numFilme": 252, "nomePT": "A Carruagem De Ouro", "nomeOriginal": "Le Carrosse d’Or"}, 
    {"numFilme": 253, "nomePT": "O Bígamo", "nomeOriginal": "The Bigamist"}, 
    {"numFilme": 254, "nomePT": "A Roda Da Fortuna", "nomeOriginal": "The Band Wagon"}, 
    {"numFilme": 255, "nomePT": "Desejos Proibidos", "nomeOriginal": "Madame De…"}, 
    {"numFilme": 256, "nomePT": "A Um Passo Da Eternidade", "nomeOriginal": "From Here to Eternity"}, 
    {"numFilme": 257, "nomePT": "Era Uma Vez Em Tóquio", "nomeOriginal": "Tokyo Story"}, 
    {"numFilme": 258, "nomePT": "A Princesa E O Plebeu", "nomeOriginal": "Roman Holiday"}, 
    {"numFilme": 259, "nomePT": "O Salário Do Medo", "nomeOriginal": "Le Salaire de la Peur"}, 
    {"numFilme": 260, "nomePT": "O Preço De Um Homem", "nomeOriginal": "The Naked Spur"}, 
    {"numFilme": 261, "nomePT": "Anjo do Mal", "nomeOriginal": "Pickup on South Street"}, 
    {"numFilme": 262, "nomePT": "Os Homens Preferem As Loiras", "nomeOriginal": "Gentlemen Prefer Blondes"}, 
    {"numFilme": 263, "nomePT": "Os Corruptos", "nomeOriginal": "The Big Heat"}, 
    {"numFilme": 264, "nomePT": "As Férias Do Sr. Hulot", "nomeOriginal": "Les Vacances de M. Hulot"}, 
    {"numFilme": 265, "nomePT": "Romance na Itália", "nomeOriginal": "Viaggio in Italia"}, 
    {"numFilme": 266, "nomePT": "Contos da Lua Vaga", "nomeOriginal": "Ugetsu Monogatari"}, 
    {"numFilme": 267, "nomePT": "Os Brutos Também Amam", "nomeOriginal": "Shane"}, 
    {"numFilme": 268, "nomePT": "O Diabo Riu Por Último", "nomeOriginal": "Beat the Devil"}, 
    {"numFilme": 269, "nomePT": "Johnny Guitar"}, 
    {"numFilme": 270, "nomePT": "Sindicato De Ladrões", "nomeOriginal": "On the Waterfront"}, 
    {"numFilme": 271, "nomePT": "Sete Noivas Para Sete Irmãos", "nomeOriginal": "Seven Brides for Seven Brothers"}, 
    {"numFilme": 272, "nomePT": "As Diabólicas", "nomeOriginal": "Les Diaboliques"}, 
    {"numFilme": 273, "nomePT": "A Relovução Dos Bichos", "nomeOriginal": "Animal Farm"}, 
    {"numFilme": 274, "nomePT": "Janela Indiscreta", "nomeOriginal": "Rear Window"}, 
    {"numFilme": 275, "nomePT": "Nasce Uma Estrela", "nomeOriginal": "A Star Is Born"}, 
    {"numFilme": 276, "nomePT": "A Condessa Descalça", "nomeOriginal": "The Barefoot Contessa"}, 
    {"numFilme": 277, "nomePT": "A Estrada Da Vida", "nomeOriginal": "La Strada"}, 
    {"numFilme": 278, "nomePT": "Os Sete Samurais", "nomeOriginal": "Shichinin No Samurai"}, 
    {"numFilme": 279, "nomePT": "Sedução da Carne", "nomeOriginal": "Senso"}, 
    {"numFilme": 280, "nomePT": "Homens Indomáveis", "nomeOriginal": "Silver Lode"}, 
    {"numFilme": 281, "nomePT": "Carmen Jones"}, 
    {"numFilme": 282, "nomePT": "O Intendente Sanshô", "nomeOriginal": "Sanshô Dayû"}, 
    {"numFilme": 283, "nomePT": "O Sal da Terra", "nomeOriginal": "Salt of the Earth"}, 
    {"numFilme": 284, "nomePT": "Artistas e Modelos", "nomeOriginal": "Artists and Models"}, 
    {"numFilme": 285, "nomePT": "Eles e Elas", "nomeOriginal": "Guys and Dolls"}, 
    {"numFilme": 286, "nomePT": "A Canção Da Estrada", "nomeOriginal": "Pather Panchali"}, 
    {"numFilme": 287, "nomePT": "Conspiração Do Silêncio", "nomeOriginal": "Bad Day At Black Rock"}, 
    {"numFilme": 288, "nomePT": "Os Mestres Loucos", "nomeOriginal": "Le Maîtres Fous"}, 
    {"numFilme": 289, "nomePT": "Hill 24 Doesn’t Answer"}, 
    {"numFilme": 290, "nomePT": "O Quinteto Da Morte", "nomeOriginal": "The Ladykillers"}, 
    {"numFilme": 291, "nomePT": "Marty"}, 
    {"numFilme": 292, "nomePT": "A Palavra", "nomeOriginal": "Ordet"}, 
    {"numFilme": 293, "nomePT": "Bob, O Jogador", "nomeOriginal": "Bob le Flambeur"}, 
    {"numFilme": 294, "nomePT": "A Morte Num Beijo", "nomeOriginal": "Kiss Me Deadly"}, 
    {"numFilme": 295, "nomePT": "Um Certo Capitão Lockhart", "nomeOriginal": "The Man From Laramie"}, 
    {"numFilme": 296, "nomePT": "Juventude Transviada", "nomeOriginal": "Rebel Without A Cause"}, 
    {"numFilme": 297, "nomePT": "Cidade do Vício", "nomeOriginal": "The Phenix City Story"}, 
    {"numFilme": 298, "nomePT": "Sorrisos De Uma Noite de Amor", "nomeOriginal": "Sommarnattens Leende"}, 
    {"numFilme": 299, "nomePT": "Noite E Neblina", "nomeOriginal": "Nuit Et Brouillard"}, 
    {"numFilme": 300, "nomePT": "O Mensageiro Do Diabo", "nomeOriginal": "The Night Of The Hunter"}, 
    {"numFilme": 301, "nomePT": "Lola Montes", "nomeOriginal": "Lola Montès"}, 
    {"numFilme": 302, "nomePT": "Planeta Proibido", "nomeOriginal": "Forbidden Planet"}, 
    {"numFilme": 303, "nomePT": "A Harpa Da Birmânia", "nomeOriginal": "Biruma no Tategoto"}, 
    {"numFilme": 304, "nomePT": "Rastros de Ódio", "nomeOriginal": "The Searchers"}, 
    {"numFilme": 305, "nomePT": "Um Condenado À Morte Escapou", "nomeOriginal": "Un Condamné À Mort S’est Échappé Ou Le Vent Sou le Où Il Veut"}, 
    {"numFilme": 306, "nomePT": "Palavras Ao Vento", "nomeOriginal": "Written On The Wind"}, 
    {"numFilme": 307, "nomePT": "O Homem Que Sabia Demais", "nomeOriginal": "The Man Who Knew Too Much"}, 
    {"numFilme": 308, "nomePT": "Assim Caminha A Humanidade", "nomeOriginal": "Giant"}, 
    {"numFilme": 309, "nomePT": "Tudo O Que O Céu Permite", "nomeOriginal": "All That Heaven Allows"}, 
    {"numFilme": 310, "nomePT": "Vampiros De Almas", "nomeOriginal": "Invasion Of The Body Snatchers"}, 
    {"numFilme": 311, "nomePT": "O Homem Errado", "nomeOriginal": "The Wrong Man"}, 
    {"numFilme": 312, "nomePT": "Delírio De Loucura", "nomeOriginal": "Bigger Than Life"}, 
    {"numFilme": 313, "nomePT": "Alta Sociedade", "nomeOriginal": "High Society"}, 
    {"numFilme": 314, "nomePT": "Os Dez Mandamentos", "nomeOriginal": "The Ten Commandments"}, 
    {"numFilme": 315, "nomePT": "Doze Homens E Uma Sentença", "nomeOriginal": "12 Angry Men"}, 
    {"numFilme": 316, "nomePT": "O Sétimo Selo", "nomeOriginal": "Det Sjunde Inseglet"}, 
    {"numFilme": 317, "nomePT": "Tarde Demais Para Esquecer", "nomeOriginal": "An Affair to Remember"}, 
    {"numFilme": 318, "nomePT": "Morangos Silvestres", "nomeOriginal": "Smultronstället"}, 
    {"numFilme": 319, "nomePT": "Noites de Cabíria", "nomeOriginal": "Le Notti Di Cabiria"}, 
    {"numFilme": 320, "nomePT": "Trono Manchado De Sangue", "nomeOriginal": "Kumonosu Jo"}, 
    {"numFilme": 321, "nomePT": "O Incrível Homem Que Encolheu", "nomeOriginal": "The Incredible Shrinking Man"}, 
    {"numFilme": 322, "nomePT": "O Invencível", "nomeOriginal": "Aparajito"}, 
    {"numFilme": 323, "nomePT": "Sem Lei, Sem Alma", "nomeOriginal": "Gunfight At The OK Corral"}, 
    {"numFilme": 324, "nomePT": "A Ponte Do Rio Kwai", "nomeOriginal": "The Bridge On The River Kwai"}, 
    {"numFilme": 325, "nomePT": "Mãe Índia", "nomeOriginal": "Bharat Mata"}, 
    {"numFilme": 326, "nomePT": "Quando Voam As Cegonhas", "nomeOriginal": "Letjat Zhuravli"}, 
    {"numFilme": 327, "nomePT": "Glória Feita De Sangue", "nomeOriginal": "Paths of Glory"}, 
    {"numFilme": 328, "nomePT": "A Embriaguez Do Sucesso", "nomeOriginal": "Sweet Smell of Success"}, 
    {"numFilme": 329, "nomePT": "O Homem Do Oeste", "nomeOriginal": "Man Of The West"}, 
    {"numFilme": 330, "nomePT": "A Marca Da Maldade", "nomeOriginal": "Touch of Evil"}, 
    {"numFilme": 331, "nomePT": "Bab El Hadid"}, 
    {"numFilme": 332, "nomePT": "Gigi"}, 
    {"numFilme": 333, "nomePT": "Acorrentados", "nomeOriginal": "The Defiant Ones"}, 
    {"numFilme": 334, "nomePT": "Um Corpo Que Cai", "nomeOriginal": "Vertigo"}, 
    {"numFilme": 335, "nomePT": "Cinzas e Diamantes", "nomeOriginal": "Popiól I Diament"}, 
    {"numFilme": 336, "nomePT": "O Vampiro Da Noite", "nomeOriginal": "Dracula"}, 
    {"numFilme": 337, "nomePT": "Meu Tio", "nomeOriginal": "Mon Oncle"}, 
    {"numFilme": 338, "nomePT": "A Sala De Música", "nomeOriginal": "Jalsaghar"}, 
    {"numFilme": 339, "nomePT": "Os Incompreendidos", "nomeOriginal": "Les Quatre Cents Coups"}, 
    {"numFilme": 340, "nomePT": "Intriga Internacional", "nomeOriginal": "North By Northwest"}, 
    {"numFilme": 341, "nomePT": "Quanto Mais Quente Melhor", "nomeOriginal": "Some Like it Hot"}, 
    {"numFilme": 342, "nomePT": "Anatomia De Um Crime", "nomeOriginal": "Anatomy of a Murder"}, 
    {"numFilme": 343, "nomePT": "Os Olhos Sem Rosto", "nomeOriginal": "Les Yeux Sans Visage"}, 
    {"numFilme": 344, "nomePT": "O Homem Que Luta Só", "nomeOriginal": "Ride Lonesome"}, 
    {"numFilme": 345, "nomePT": "Orfeu Negro"}, 
    {"numFilme": 346, "nomePT": "Sombras", "nomeOriginal": "Shadows"}, 
    {"numFilme": 347, "nomePT": "O Mundo de Apu", "nomeOriginal": "Apur Sansar"}, 
    {"numFilme": 348, "nomePT": "Acossado", "nomeOriginal": "A Bout de Souffle"}, 
    {"numFilme": 349, "nomePT": "Ben-Hur"}, 
    {"numFilme": 350, "nomePT": "Pickpocket:  O Batedor De Carteiras", "nomeOriginal": "Pickpocket"}, 
    {"numFilme": 351, "nomePT": "Hiroshima Meu Amor", "nomeOriginal": "Hiroshima Mon Amour"}, 
    {"numFilme": 352, "nomePT": "Onde Começa o Inferno", "nomeOriginal": "Rio Bravo"}, 
    {"numFilme": 353, "nomePT": "A Um Passo Da Liberdade", "nomeOriginal": "Le Trou"}, 
    {"numFilme": 354, "nomePT": "Ervas Flutuantes", "nomeOriginal": "Ukigusa"}, 
    {"numFilme": 355, "nomePT": "Rocco E Seus Irmãos", "nomeOriginal": "Rocco E I Suoi Fratelli"}, 
    {"numFilme": 356, "nomePT": "A Doce Vida", "nomeOriginal": "La Dolce Vita"}, 
    {"numFilme": 357, "nomePT": "Tudo Começou no Sábado", "nomeOriginal": "Saturday Night And Sunday Morning"}, 
    {"numFilme": 358, "nomePT": "Atirem No Pianista", "nomeOriginal": "Tirez Sur le Pianiste"}, 
    {"numFilme": 359, "nomePT": "A Aventura", "nomeOriginal": "L’Avventura"}, 
    {"numFilme": 360, "nomePT": "A Adolescente", "nomeOriginal": "La Joven"}, 
    {"numFilme": 361, "nomePT": "Meghe Dhaka Tara"}, 
    {"numFilme": 362, "nomePT": "Hanyo"}, 
    {"numFilme": 363, "nomePT": "Psicose", "nomeOriginal": "Psycho"}, 
    {"numFilme": 364, "nomePT": "A Maldição Do Demônio", "nomeOriginal": "La Maschera Del Demonio"}, 
    {"numFilme": 365, "nomePT": "A Tortura Do Medo", "nomeOriginal": "Peeping Tom"}, 
    {"numFilme": 366, "nomePT": "Se Meu Apartamento Falasse", "nomeOriginal": "The Apartment"}, 
    {"numFilme": 367, "nomePT": "Spartacus"}, 
    {"numFilme": 368, "nomePT": "Clamor Do Sexo", "nomeOriginal": "Splendor in the Grass"}, 
    {"numFilme": 369, "nomePT": "O Ano Passado Em Marienbad", "nomeOriginal": "L’Année Dernière à Marienbad"}, 
    {"numFilme": 370, "nomePT": "La Jetée"}, 
    {"numFilme": 371, "nomePT": "A Face Oculta", "nomeOriginal": "One-Eyed Jacks"}, 
    {"numFilme": 372, "nomePT": "Lola, A Flor Proibida", "nomeOriginal": "Lola"}, 
    {"numFilme": 373, "nomePT": "Bonequinha De Luxo", "nomeOriginal": "Breakfast at Tiffany’s"}, 
    {"numFilme": 374, "nomePT": "A Noite", "nomeOriginal": "La Notte"}, 
    {"numFilme": 375, "nomePT": "Jules E Jim:  Uma Mulher Para Dois", "nomeOriginal": "Jules et Jim"}, 
    {"numFilme": 376, "nomePT": "Viridiana"}, 
    {"numFilme": 377, "nomePT": "O Terror Das Mulheres", "nomeOriginal": "The Ladies Man"}, 
    {"numFilme": 378, "nomePT": "Através Do Espelho", "nomeOriginal": "Såsom I En Spegel"}, 
    {"numFilme": 379, "nomePT": "Crônica de um Verão", "nomeOriginal": "Chronique d’Un Été"}, 
    {"numFilme": 380, "nomePT": "Desafio À Corrupção", "nomeOriginal": "The Hustler"}, 
    {"numFilme": 381, "nomePT": "Amor Sublime Amor", "nomeOriginal": "West Side Story"}, 
    {"numFilme": 382, "nomePT": "Mundo Cão", "nomeOriginal": "Mondo Cane"}, 
    {"numFilme": 383, "nomePT": "Cléo De 5 às 7", "nomeOriginal": "Cléo De 5 à 7"}, 
    {"numFilme": 384, "nomePT": "Dog Star Man"}, 
    {"numFilme": 385, "nomePT": "A Rotina Tem Seu Encanto", "nomeOriginal": "Sanman no Aji"}, 
    {"numFilme": 386, "nomePT": "O Eclipse", "nomeOriginal": "L’Eclisse"}, 
    {"numFilme": 387, "nomePT": "Lawrence da Arábia", "nomeOriginal": "Lawrence of Arabia"}, 
    {"numFilme": 388, "nomePT": "O Sol É Para Todos", "nomeOriginal": "To Kill A Mockingbird"}, 
    {"numFilme": 389, "nomePT": "Sob O Domínio Do Mal", "nomeOriginal": "The Manchurian Candidate"}, 
    {"numFilme": 390, "nomePT": "Lolita"}, 
    {"numFilme": 391, "nomePT": "O Pagador de Promessas"}, 
    {"numFilme": 392, "nomePT": "O Homem Que Matou O Facínora", "nomeOriginal": "The Man Who Shot Liberty Valance"}, 
    {"numFilme": 393, "nomePT": "O Que Terá Acontecido A Baby Jane?", "nomeOriginal": "What Ever Happened to Baby Jane?"}, 
    {"numFilme": 394, "nomePT": "Viver A Vida", "nomeOriginal": "Vivre Sa Vie:  Film en Douze Tableaux"}, 
    {"numFilme": 395, "nomePT": "Heaven And Earth Magic"}, 
    {"numFilme": 396, "nomePT": "Os Pássaros", "nomeOriginal": "The Birds"}, 
    {"numFilme": 397, "nomePT": "O Professor Aloprado", "nomeOriginal": "The Nutty Professor"}, 
    {"numFilme": 398, "nomePT": "Blonde Cobra"}, 
    {"numFilme": 399, "nomePT": "The Cool World"}, 
    {"numFilme": 400, "nomePT": "Fellini 8 1/2", "nomeOriginal": "8 1/2"}, 
    {"numFilme": 401, "nomePT": "A Passageira", "nomeOriginal": "Pasazerka"}, 
    {"numFilme": 402, "nomePT": "O Desprezo", "nomeOriginal": "Le Mépris"}, 
    {"numFilme": 403, "nomePT": "O Indomado", "nomeOriginal": "Hud"}, 
    {"numFilme": 404, "nomePT": "Luz De Inverno", "nomeOriginal": "Nattvardsgästerna"}, 
    {"numFilme": 405, "nomePT": "Criaturas Flamejantes", "nomeOriginal": "Flaming Creatures"}, 
    {"numFilme": 406, "nomePT": "A Grande Escapada", "nomeOriginal": "The Great Escape"}, 
    {"numFilme": 407, "nomePT": "Paixões Que Alucinam", "nomeOriginal": "Shock Corridor"}, 
    {"numFilme": 408, "nomePT": "O Leopardo", "nomeOriginal": "Il Gattopardo"}, 
    {"numFilme": 409, "nomePT": "Vidas Secas"}, 
    {"numFilme": 410, "nomePT": "Méditerranée"}, 
    {"numFilme": 411, "nomePT": "Khaneh Siah Ast"}, 
    {"numFilme": 412, "nomePT": "Desafio do Além", "nomeOriginal": "The Haunting"}, 
    {"numFilme": 413, "nomePT": "A Vingança do Ator", "nomeOriginal": "Yukinojo Henge"}, 
    {"numFilme": 414, "nomePT": "O Criado", "nomeOriginal": "The Servant"}, 
    {"numFilme": 415, "nomePT": "007 Contra Goldfinger", "nomeOriginal": "Goldfinger"}, 
    {"numFilme": 416, "nomePT": "Scorpio Rising"}, 
    {"numFilme": 417, "nomePT": "Os Guarda-Chuvas do Amor", "nomeOriginal": "Les Parapluies de Cherbourg"}, 
    {"numFilme": 418, "nomePT": "Marnie, Confissões de Uma Ladra", "nomeOriginal": "Marnie"}, 
    {"numFilme": 419, "nomePT": "Minha Bela Dama", "nomeOriginal": "My Fair Lady"}, 
    {"numFilme": 420, "nomePT": "A Mulher de Areia", "nomeOriginal": "Suna No Onna"}, 
    {"numFilme": 421, "nomePT": "Dr. Fantástico ou Como Aprendi a Parar de Me Preocupar e Amar a Bomba", "nomeOriginal": "Dr. Stragelove Or:  How I Learned To Stop Worrying And Love The Bomb"}, 
    {"numFilme": 422, "nomePT": "Os Reis do IÊ IÊ IÊ", "nomeOriginal": "A Hard Day’s Night"}, 
    {"numFilme": 423, "nomePT": "O Deserto Vermelho", "nomeOriginal": "Il Deserto Rosso"}, 
    {"numFilme": 424, "nomePT": "Os Cavalos de Fogo", "nomeOriginal": "Tini Zabutykh Predkiv"}, 
    {"numFilme": 425, "nomePT": "A Máscara Mortal", "nomeOriginal": "The Masque Of The Red Death"}, 
    {"numFilme": 426, "nomePT": "Antes da Revolução", "nomeOriginal": "Prima Della Rivoluzione"}, 
    {"numFilme": 427, "nomePT": "Gertrud"}, 
    {"numFilme": 428, "nomePT": "O Evangelho Segundo São Mateus", "nomeOriginal": "Il Vangelo Secondo Matteo"}, 
    {"numFilme": 429, "nomePT": "Deus E O Diabo Na Terra Do Sol"}, 
    {"numFilme": 430, "nomePT": "Onibaba:  A Mulher Demônio", "nomeOriginal": "Onibaba"}, 
    {"numFilme": 431, "nomePT": "Vinyl"}, 
    {"numFilme": 432, "nomePT": "A Loja da Rua Principal", "nomeOriginal": "Obchod Na Korze"}, 
    {"numFilme": 433, "nomePT": "Doutor Jivago", "nomeOriginal": "Doctor Zhivago"}, 
    {"numFilme": 434, "nomePT": "The War Game"}, 
    {"numFilme": 435, "nomePT": "A Hora E A Vez De Augusto Matraga"}, 
    {"numFilme": 436, "nomePT": "A Batalha Da Argélia", "nomeOriginal": "La Battaglia Di Algeri"}, 
    {"numFilme": 437, "nomePT": "A Noviça Rebelde", "nomeOriginal": "The Sound Of Music"}, 
    {"numFilme": 438, "nomePT": "O Manuscrito De Saragoça", "nomeOriginal": "Rekopis Znaleziony W Saragossie"}, 
    {"numFilme": 439, "nomePT": "Alphaville", "nomeOriginal": "Alphaville, Une Étrange Aventure De Lemmy Caution"}, 
    {"numFilme": 440, "nomePT": "Baladas À Meia-Noite", "nomeOriginal": "Campanadas A Medianoche"}, 
    {"numFilme": 441, "nomePT": "Repulsa Ao Sexo", "nomeOriginal": "Repulsion"}, 
    {"numFilme": 442, "nomePT": "Julieta Dos Espíritos", "nomeOriginal": "Giulietta Degli Spiriti"}, 
    {"numFilme": 443, "nomePT": "O Demônio Das Onze Horas", "nomeOriginal": "Pierrot Le Fou"}, 
    {"numFilme": 444, "nomePT": "Faster, Pussycat! Kill! Kill!"}, 
    {"numFilme": 445, "nomePT": "Subarnarekha"}, 
    {"numFilme": 446, "nomePT": "O Homem Da Cabeça Raspada", "nomeOriginal": "De Man Die Zijn Haar Kort Liet Knippen"}, 
    {"numFilme": 447, "nomePT": "Hold Me While I’m Naked"}, 
    {"numFilme": 448, "nomePT": "Blow Up:  Depois Daquele Beijo", "nomeOriginal": "Blow Up"}, 
    {"numFilme": 449, "nomePT": "Três Homens Em Conflito", "nomeOriginal": "Il Buono, Il Brutto, Il Cattivo"}, 
    {"numFilme": 450, "nomePT": "As Pequenas Margaridas", "nomeOriginal": "Sedmikrasky"}, 
    {"numFilme": 451, "nomePT": "Da Zui Xia"}, 
    {"numFilme": 452, "nomePT": "O Segundo Rosto", "nomeOriginal": "Seconds"}, 
    {"numFilme": 453, "nomePT": "No Calor Da Noite", "nomeOriginal": "In The Heat Of The Night"}, 
    {"numFilme": 454, "nomePT": "Quem Tem Medo De Virginia Woolf?", "nomeOriginal": "Who’s Afraid Of Virginia Woolf?"}, 
    {"numFilme": 455, "nomePT": "Persona"}, 
    {"numFilme": 456, "nomePT": "Masculino-Feminino", "nomeOriginal": "Masculin, Féminin"}, 
    {"numFilme": 457, "nomePT": "A Grande Testemunha", "nomeOriginal": "Au Hasard Balthazar"}, 
    {"numFilme": 458, "nomePT": "Duas Ou Três Coisas Que Eu Sei Dela", "nomeOriginal": "2 ou 3 Choses Que Je Sais D’Elle"}, 
    {"numFilme": 459, "nomePT": "A Primeira Noite De Um Homem", "nomeOriginal": "The Graduate"}, 
    {"numFilme": 460, "nomePT": "Playtime"}, 
    {"numFilme": 461, "nomePT": "Report"}, 
    {"numFilme": 462, "nomePT": "Hombre"}, 
    {"numFilme": 463, "nomePT": "A Bela Da Tarde", "nomeOriginal": "Belle de Jour"}, 
    {"numFilme": 464, "nomePT": "Duas Garotas Românticas", "nomeOriginal": "Les Demoiselles de Rochefort"}, 
    {"numFilme": 465, "nomePT": "Week-End À Francesa", "nomeOriginal": "Week-End"}, 
    {"numFilme": 466, "nomePT": "O Samurai", "nomeOriginal": "Le Samourai"}, 
    {"numFilme": 467, "nomePT": "Rebeldia Indomável", "nomeOriginal": "Cool Hand Luke"}, 
    {"numFilme": 468, "nomePT": "À Queima Roupa", "nomeOriginal": "Point Blank"}, 
    {"numFilme": 469, "nomePT": "Wavelength"}, 
    {"numFilme": 470, "nomePT": "Bonnie E Clyde:  Uma Rajada De Balas", "nomeOriginal": "Bonnie And Clyde"}, 
    {"numFilme": 471, "nomePT": "Csillagosok, Katonák"}, 
    {"numFilme": 472, "nomePT": "Marketa Lazarová"}, 
    {"numFilme": 473, "nomePT": "Mogli:  O Menino Lobo", "nomeOriginal": "The Jungle Book"}, 
    {"numFilme": 474, "nomePT": "O Baile Dos Bombeiros", "nomeOriginal": "Horí, Má Panenko"}, 
    {"numFilme": 475, "nomePT": "Terra Em Transe"}, 
    {"numFilme": 476, "nomePT": "Trens Estreitamente Vigiados", "nomeOriginal": "Ostre Sledované Vlaky"}, 
    {"numFilme": 477, "nomePT": "Vij, O Espírito do Mal", "nomeOriginal": "Vij"}, 
    {"numFilme": 478, "nomePT": "A Vaca", "nomeOriginal": "Gaav"}, 
    {"numFilme": 479, "nomePT": "Era uma Vez no Oeste", "nomeOriginal": "C’era una Volta il West"}, 
    {"numFilme": 480, "nomePT": "O Planeta dos Macacos", "nomeOriginal": "Planet of the Apes"}, 
    {"numFilme": 481, "nomePT": "Faces"}, 
    {"numFilme": 482, "nomePT": "O Bebê de Rosemary", "nomeOriginal": "Rosemary’s Baby"}, 
    {"numFilme": 483, "nomePT": "Se…", "nomeOriginal": "If…"}, 
    {"numFilme": 484, "nomePT": "Memórias do Subdesenvolvimento", "nomeOriginal": "Memorias del Subdesarrollo"}, 
    {"numFilme": 485, "nomePT": "Primavera Para Hitler", "nomeOriginal": "The Producers"}, 
    {"numFilme": 486, "nomePT": "O Bandido da Luz Vermelha"}, 
    {"numFilme": 487, "nomePT": "Vergonha", "nomeOriginal": "Skammen"}, 
    {"numFilme": 488, "nomePT": ", Uma Odisséia no Espaço", "nomeOriginal": ":  A Space Odyssey"}, 
    {"numFilme": 489, "nomePT": "A Hora do Lobo", "nomeOriginal": "Vargtimmen"}, 
    {"numFilme": 490, "nomePT": "Na Mira da Morte", "nomeOriginal": "Targets"}, 
    {"numFilme": 491, "nomePT": "A Noite dos Mortos Vivos", "nomeOriginal": "Night of the Living Dead"}, 
    {"numFilme": 492, "nomePT": "Minha Noite Com Ela", "nomeOriginal": "Ma Nuit Chez Maud"}, 
    {"numFilme": 493, "nomePT": "Lucía"}, 
    {"numFilme": 494, "nomePT": "Hsia Nu"}, 
    {"numFilme": 495, "nomePT": "Butch Cassidy", "nomeOriginal": "Butch Cassidy and the Sundance Kid"}, 
    {"numFilme": 496, "nomePT": "Perdidos na Noite", "nomeOriginal": "Midnight Cowboy"}, 
    {"numFilme": 497, "nomePT": "Satyricon"}, 
    {"numFilme": 498, "nomePT": "Z"}, 
    {"numFilme": 499, "nomePT": "O Conformista", "nomeOriginal": "Il Conformista"}, 
    {"numFilme": 500, "nomePT": "Sem Destino", "nomeOriginal": "Easy Rider"}, 
    {"numFilme": 501, "nomePT": "High School"}, 
    {"numFilme": 502, "nomePT": "In the Year of the Pig"}, 
    {"numFilme": 503, "nomePT": "Meu Ódio Será Tua Herança", "nomeOriginal": "The Wild Bunch"}, 
    {"numFilme": 504, "nomePT": "Andrei Rublev", "nomeOriginal": "Andrei Rublyov"}, 
    {"numFilme": 505, "nomePT": "Macunaíma"}, 
    {"numFilme": 506, "nomePT": "A Cor da Romã", "nomeOriginal": "Sayat Nova"}, 
    {"numFilme": 507, "nomePT": "Kes"}, 
    {"numFilme": 508, "nomePT": "Tristana, Uma Paixão Mórbida", "nomeOriginal": "Tristana"}, 
    {"numFilme": 509, "nomePT": "Cada um Vive Como Quer", "nomeOriginal": "Five Easy Pieces"}, 
    {"numFilme": 510, "nomePT": "El Topo"}, 
    {"numFilme": 511, "nomePT": "Woodstock, Onde Tudo Começou", "nomeOriginal": "Woodstock"}, 
    {"numFilme": 512, "nomePT": "Ato Final", "nomeOriginal": "Deep End"}, 
    {"numFilme": 513, "nomePT": "A Estratégia da Aranha", "nomeOriginal": "La Strategia del Ragno"}, 
    {"numFilme": 514, "nomePT": "Pequeno Grande Homem", "nomeOriginal": "Little Big Man"}, 
    {"numFilme": 515, "nomePT": "Orelha", "nomeOriginal": "Ucho"}, 
    {"numFilme": 516, "nomePT": "Patton:  Rebelde ou Herói?", "nomeOriginal": "Patton"}, 
    {"numFilme": 517, "nomePT": "M*A*S*H"}, 
    {"numFilme": 518, "nomePT": "Performance"}, 
    {"numFilme": 519, "nomePT": "Gimme Shelter"}, 
    {"numFilme": 520, "nomePT": "Zabriskie Point"}, 
    {"numFilme": 521, "nomePT": "O Pássaro das Plumas de Cristal", "nomeOriginal": "L’uccello Dalle Piume di Cristallo"}, 
    {"numFilme": 522, "nomePT": "O Jardim dos Finzi-Contini", "nomeOriginal": "Il Giardino Dei Finzi-Contini"}, 
    {"numFilme": 523, "nomePT": "Wanda"}, 
    {"numFilme": 524, "nomePT": "W.R.:  Misterije Organizma"}, 
    {"numFilme": 525, "nomePT": "Laranja Mecânica", "nomeOriginal": "A Clockwork Orange"}, 
    {"numFilme": 526, "nomePT": "Le Chagrin Et La Pitié"}, 
    {"numFilme": 527, "nomePT": "A Fantástica Fábrica de Chocolate", "nomeOriginal": "Willy Wonka and the Chocolate Factory"}, 
    {"numFilme": 528, "nomePT": "Jogos e Trapaças:  Quando os Homens são Homens", "nomeOriginal": "McCabe and Mrs. Miller"}, 
    {"numFilme": 529, "nomePT": "A Longa Caminhada", "nomeOriginal": "Walkabout"}, 
    {"numFilme": 530, "nomePT": "Klute, O Passado Condena", "nomeOriginal": "Klute"}, 
    {"numFilme": 531, "nomePT": "Ensina-me a Viver", "nomeOriginal": "Harold and Maude"}, 
    {"numFilme": 532, "nomePT": "Salmo Vermelho", "nomeOriginal": "Még Kér a Nép"}, 
    {"numFilme": 533, "nomePT": "Carter, O Vingador", "nomeOriginal": "Get Carter"}, 
    {"numFilme": 534, "nomePT": "Operação França", "nomeOriginal": "The French Connection"}, 
    {"numFilme": 535, "nomePT": "Shaft"}, 
    {"numFilme": 536, "nomePT": "Perseguidor Implacável", "nomeOriginal": "Dirty Harry"}, 
    {"numFilme": 537, "nomePT": "O Sopro no Coração", "nomeOriginal": "Le Souffle Au Coeur"}, 
    {"numFilme": 538, "nomePT": "Sweet Sweetback’s Baadasssss Song"}, 
    {"numFilme": 539, "nomePT": "A Última Sessão de Cinema", "nomeOriginal": "The Last Picture Show"}, 
    {"numFilme": 540, "nomePT": "Sob o Domínio do Medo", "nomeOriginal": "Straw Dogs"}, 
    {"numFilme": 541, "nomePT": "Corrida Sem Fim", "nomeOriginal": "Two-Lane Blacktop"}, 
    {"numFilme": 542, "nomePT": "O Rapaz Que Partia Corações", "nomeOriginal": "The Heartbreak Kid"}, 
    {"numFilme": 543, "nomePT": "Aguirre, A Cólera dos Deuses", "nomeOriginal": "Aguirre, Der Zorn Gottes"}, 
    {"numFilme": 544, "nomePT": "Cabaret"}, 
    {"numFilme": 545, "nomePT": "O Último Tango em Paris", "nomeOriginal": "Ultimo Tango a Parigi"}, 
    {"numFilme": 546, "nomePT": "O Estranho Sem Nome", "nomeOriginal": "High Plains Drifter"}, 
    {"numFilme": 547, "nomePT": "Jogo Mortal", "nomeOriginal": "Sleuth"}, 
    {"numFilme": 548, "nomePT": "Amargo Pesadelo", "nomeOriginal": "Deliverance"}, 
    {"numFilme": 549, "nomePT": "Solaris", "nomeOriginal": "Solyaris"}, 
    {"numFilme": 550, "nomePT": "O Poderoso Chefão", "nomeOriginal": "The Godfather"}, 
    {"numFilme": 551, "nomePT": "Gritos e Sussuros", "nomeOriginal": "Viskingar Och Rop"}, 
    {"numFilme": 552, "nomePT": "Cidade das Ilusões", "nomeOriginal": "Fat City"}, 
    {"numFilme": 553, "nomePT": "O Discreto Charme da Burguesia", "nomeOriginal": "Le Charme Discret de la Bourgeoisie"}, 
    {"numFilme": 554, "nomePT": "As Lágrimas Amargas de Petra Von Kant", "nomeOriginal": "Die Bitteren Tränen der Petra Von Kant"}, 
    {"numFilme": 555, "nomePT": "Frenesi", "nomeOriginal": "Frenzy"}, 
    {"numFilme": 556, "nomePT": "Pink Flamingos"}, 
    {"numFilme": 557, "nomePT": "Superfly"}, 
    {"numFilme": 558, "nomePT": "Golpe de Mestre", "nomeOriginal": "The Sting"}, 
    {"numFilme": 559, "nomePT": "A Mãe e a Puta", "nomeOriginal": "La Maman et la Putain"}, 
    {"numFilme": 560, "nomePT": "Terra de Ninguém", "nomeOriginal": "Badlands"}, 
    {"numFilme": 561, "nomePT": "Loucuras de Verão", "nomeOriginal": "American Graffiti"}, 
    {"numFilme": 562, "nomePT": "Papillon"}, 
    {"numFilme": 563, "nomePT": "Operação Dragão", "nomeOriginal": "Enter the Dragon"}, 
    {"numFilme": 564, "nomePT": "Caminhos Perigosos", "nomeOriginal": "Mean Streets"}, 
    {"numFilme": 565, "nomePT": "O Perigoso Adeus", "nomeOriginal": "The Long Goodbye"}, 
    {"numFilme": 566, "nomePT": "O Homem de Palha", "nomeOriginal": "The Wicker Man"}, 
    {"numFilme": 567, "nomePT": "A Noite Americana", "nomeOriginal": "La Nuit Américaine"}, 
    {"numFilme": 568, "nomePT": "Inverno de Sangue em Veneza", "nomeOriginal": "Don’t Look Now"}, 
    {"numFilme": 569, "nomePT": "O Dorminhoco", "nomeOriginal": "Sleeper"}, 
    {"numFilme": 570, "nomePT": "Serpico"}, 
    {"numFilme": 571, "nomePT": "O Exorcista", "nomeOriginal": "The Exorcist"}, 
    {"numFilme": 572, "nomePT": "Louca Paixão", "nomeOriginal": "Turks Fruit"}, 
    {"numFilme": 573, "nomePT": "O Espírito da Colmeia", "nomeOriginal": "El Espíritu de la Colmena"}, 
    {"numFilme": 574, "nomePT": "O PLaneta Selvagem", "nomeOriginal": "La Planète Sauvage"}, 
    {"numFilme": 575, "nomePT": "Amarcord"}, 
    {"numFilme": 576, "nomePT": "Querem Meu Sangue", "nomeOriginal": "The Harder They Come"}, 
    {"numFilme": 577, "nomePT": "Pat Garrett e Billy The Kid", "nomeOriginal": "Pat Garrett and Billy the Kid"}, 
    {"numFilme": 578, "nomePT": "Dersu Uzala"}, 
    {"numFilme": 579, "nomePT": "A Conversação", "nomeOriginal": "The Conversation"}, 
    {"numFilme": 580, "nomePT": "O Massacre da Serra Elétrica", "nomeOriginal": "The Texas Chain Saw Massacre"}, 
    {"numFilme": 581, "nomePT": "O Espelho", "nomeOriginal": "Zerkalo"}, 
    {"numFilme": 582, "nomePT": "Uma Mulher Sob Influência", "nomeOriginal": "A Woman Under the Influence"}, 
    {"numFilme": 583, "nomePT": "Jovem Frankenstein", "nomeOriginal": "Young Frankenstein"}, 
    {"numFilme": 584, "nomePT": "Chinatown"}, 
    {"numFilme": 585, "nomePT": "Céline et Julie Vont en Bateau"}, 
    {"numFilme": 586, "nomePT": "Banzé no Oeste", "nomeOriginal": "Blazing Saddles"}, 
    {"numFilme": 587, "nomePT": "O Poderoso Chefão 2", "nomeOriginal": "The Godfather:  Part II"}, 
    {"numFilme": 588, "nomePT": "O Medo Devora a Alma", "nomeOriginal": "Angst Essen Seele Auf"}, 
    {"numFilme": 589, "nomePT": "Traga-me a Cabeça de Alfredo Garcia", "nomeOriginal": "Bring Me the Head of Alfredo Garcia"}, 
    {"numFilme": 590, "nomePT": "Um Dia de Cão", "nomeOriginal": "Dog Day Afternoon"}, 
    {"numFilme": 591, "nomePT": "Um Estranho no Ninho", "nomeOriginal": "One Flew Over the Cuckoo’s Nest"}, 
    {"numFilme": 592, "nomePT": "Jeanne Dielman", "nomeOriginal": "Jeanne Dielman, 23 Quai Du Commerce, 1080 Bruxelles"}, 
    {"numFilme": 593, "nomePT": "The Rocky Horror Picture Show", "nomeOriginal": "The Rocky Horror Picture Show"}, 
    {"numFilme": 594, "nomePT": "Deewaar"}, 
    {"numFilme": 595, "nomePT": "Monty Python:  Em Busca do Cálice Sagrado", "nomeOriginal": "Monty Python and the Holy Grail"}, 
    {"numFilme": 596, "nomePT": "Barry Lyndon"}, 
    {"numFilme": 597, "nomePT": "O Direito do Mais Forte", "nomeOriginal": "Faustrecht Der Freiheit"}, 
    {"numFilme": 598, "nomePT": "India Song"}, 
    {"numFilme": 599, "nomePT": "Piquenique na Montanha Misteriosa", "nomeOriginal": "Picnic at Hanging Rock"}, 
    {"numFilme": 600, "nomePT": "Maynila:  Sa Mga Kuko Ng Liwanag"}, 
    {"numFilme": 601, "nomePT": "Os 120 Dias de Sodoma", "nomeOriginal": "Salò o Le Centoventi Giornate di Sodoma"}, 
    {"numFilme": 602, "nomePT": "Nashville"}, 
    {"numFilme": 603, "nomePT": "Cría Cuervos"}, 
    {"numFilme": 604, "nomePT": "A Viagem dos Comediantes", "nomeOriginal": "O Thiassos"}, 
    {"numFilme": 605, "nomePT": "Tubarão", "nomeOriginal": "Jaws"}, 
    {"numFilme": 606, "nomePT": "A Morte de um Bookmaker Chinês", "nomeOriginal": "The Killing of a Chinese Bookie"}, 
    {"numFilme": 607, "nomePT": "Carrie, a Estranha", "nomeOriginal": "Carrie"}, 
    {"numFilme": 608, "nomePT": "Dona Flor e Seus Dois Maridos"}, 
    {"numFilme": 609, "nomePT": "Todos os Homens do Presidente", "nomeOriginal": "All the President’s Men"}, 
    {"numFilme": 610, "nomePT": "Rocky, um Lutador", "nomeOriginal": "Rocky"}, 
    {"numFilme": 611, "nomePT": "Taxi Driver"}, 
    {"numFilme": 612, "nomePT": "Rede de Intrigas", "nomeOriginal": "Network"}, 
    {"numFilme": 613, "nomePT": "Voskhozhdeniye"}, 
    {"numFilme": 614, "nomePT": "O Império dos Sentidos", "nomeOriginal": "Ai no Corrida"}, 
    {"numFilme": 615, "nomePT": "1900", "nomeOriginal": "Novecento"}, 
    {"numFilme": 616, "nomePT": "O Homem Que Caiu na Terra", "nomeOriginal": "The Man Who Fell to Earth"}, 
    {"numFilme": 617, "nomePT": "Guerra nas Estrelas", "nomeOriginal": "Star Wars"}, 
    {"numFilme": 618, "nomePT": "Contatos Imediatos de Terceiro Grau", "nomeOriginal": "Close Encounters of the Third Kind"}, 
    {"numFilme": 619, "nomePT": "The Last Wave"}, 
    {"numFilme": 620, "nomePT": "Noivo Neurótico, Noiva Nervosa", "nomeOriginal": "Annie Hall"}, 
    {"numFilme": 621, "nomePT": "Last Chants for a Slow Dance"}, 
    {"numFilme": 622, "nomePT": "Stroszek"}, 
    {"numFilme": 623, "nomePT": "O Homem de Mármore", "nomeOriginal": "Czlowiek Z Marmuru"}, 
    {"numFilme": 624, "nomePT": "Os Embalos de Sábado à Noite", "nomeOriginal": "Saturday Night Fever"}, 
    {"numFilme": 625, "nomePT": "Killer of Sheep"}, 
    {"numFilme": 626, "nomePT": "Eraserhead"}, 
    {"numFilme": 627, "nomePT": "Ceddo"}, 
    {"numFilme": 628, "nomePT": "O Amigo Americano", "nomeOriginal": "Der Amerikanische Freund"}, 
    {"numFilme": 629, "nomePT": "Viagem Maldita", "nomeOriginal": "The Hills Have Eyes"}, 
    {"numFilme": 630, "nomePT": "Soldado de Laranja", "nomeOriginal": "Soldaat Van Oranje"}, 
    {"numFilme": 631, "nomePT": "Suspiria"}, 
    {"numFilme": 632, "nomePT": "O Canto de Jimmie Blacksmith", "nomeOriginal": "The Chant of Jimmie Blacksmith"}, 
    {"numFilme": 633, "nomePT": "Os Cinco Venenos", "nomeOriginal": "Wu Du"}, 
    {"numFilme": 634, "nomePT": "A Árvore dos Tamancos", "nomeOriginal": "L’Albero Degli Zoccoli"}, 
    {"numFilme": 635, "nomePT": "O Franco Atirador", "nomeOriginal": "The Deer Hunter"}, 
    {"numFilme": 636, "nomePT": "Grease:  Nos Tempos da Brilhantina", "nomeOriginal": "Grease"}, 
    {"numFilme": 637, "nomePT": "Cinzas do Paraíso", "nomeOriginal": "Days of Heaven"}, 
    {"numFilme": 638, "nomePT": "O Despertar dos Mortos", "nomeOriginal": "Dawn of the Dead"}, 
    {"numFilme": 639, "nomePT": "Shao Lin San Shi Liu Fang"}, 
    {"numFilme": 640, "nomePT": "Up In Smoke"}, 
    {"numFilme": 641, "nomePT": "Halloween:  A Noite de Terror", "nomeOriginal": "Halloween"}, 
    {"numFilme": 642, "nomePT": "O Casamento de Maria Braun", "nomeOriginal": "Die Ehe Der Maria Braun"}, 
    {"numFilme": 643, "nomePT": "Bye Bye Brasil"}, 
    {"numFilme": 644, "nomePT": "My Brilliant Career"}, 
    {"numFilme": 645, "nomePT": "Stalker"}, 
    {"numFilme": 646, "nomePT": "Alien, O Oitavo Passageiro", "nomeOriginal": "Alien"}, 
    {"numFilme": 647, "nomePT": "O Vencedor", "nomeOriginal": "Breaking Away"}, 
    {"numFilme": 648, "nomePT": "O Tambor", "nomeOriginal": "Die Blechtrommel"}, 
    {"numFilme": 649, "nomePT": "All That Jazz"}, 
    {"numFilme": 650, "nomePT": "Muito Além do Jardim", "nomeOriginal": "Being There"}, 
    {"numFilme": 651, "nomePT": "Kramer Vs. Kramer"}, 
    {"numFilme": 652, "nomePT": "A Vida de Brian", "nomeOriginal": "Life of Brian"}, 
    {"numFilme": 653, "nomePT": "Apocalypse Now"}, 
    {"numFilme": 654, "nomePT": "O Panaca", "nomeOriginal": "The Jerk"}, 
    {"numFilme": 655, "nomePT": "Muppets:  O Filme", "nomeOriginal": "The Muppet Movie"}, 
    {"numFilme": 656, "nomePT": "Manhattan"}, 
    {"numFilme": 657, "nomePT": "Mad Max"}, 
    {"numFilme": 658, "nomePT": "Nosferatu:  O Vampiro da Noite", "nomeOriginal": "Nosferatu:  Phantom der Nacht"}, 
    {"numFilme": 659, "nomePT": "Gente Como a Gente", "nomeOriginal": "Ordinary People"}, 
    {"numFilme": 660, "nomePT": "Atlantic City"}, 
    {"numFilme": 661, "nomePT": "O Último Metrô", "nomeOriginal": "Le Dernier Métro"}, 
    {"numFilme": 662, "nomePT": "O Iluminado", "nomeOriginal": "The Shining"}, 
    {"numFilme": 663, "nomePT": "Guerra nas Estrelas:  Episódio V - O Império Contra-Ataca", "nomeOriginal": "Star Wars:  Episode V - The Empire Strikes Back"}, 
    {"numFilme": 664, "nomePT": "O Homem-Elefante", "nomeOriginal": "The Elephant Man"}, 
    {"numFilme": 665, "nomePT": "Agonia e Glória", "nomeOriginal": "The Big Red One"}, 
    {"numFilme": 666, "nomePT": "Loulou"}, 
    {"numFilme": 667, "nomePT": "Apertem os Cintos, O Piloto Sumiu", "nomeOriginal": "Airplane!"}, 
    {"numFilme": 668, "nomePT": "Touro Indomável", "nomeOriginal": "Raging Bull"}, 
    {"numFilme": 669, "nomePT": "Caçadores da Arca Perdida", "nomeOriginal": "Raiders of the Lost Ark"}, 
    {"numFilme": 670, "nomePT": "O Barco:  Inferno em Alto-Mar", "nomeOriginal": "Das Boot"}, 
    {"numFilme": 671, "nomePT": "Gallipoli"}, 
    {"numFilme": 672, "nomePT": "Carruagens de Fogo", "nomeOriginal": "Chariots of Fire"}, 
    {"numFilme": 673, "nomePT": "Corpos Ardentes", "nomeOriginal": "Body Heat"}, 
    {"numFilme": 674, "nomePT": "Reds"}, 
    {"numFilme": 675, "nomePT": "Pixote"}, 
    {"numFilme": 676, "nomePT": "Três Irmãos", "nomeOriginal": "Tre Fratelli"}, 
    {"numFilme": 677, "nomePT": "O Homem de Ferro", "nomeOriginal": "Czlowiek Z Zelaza"}, 
    {"numFilme": 678, "nomePT": "Eles Não Usam Black-Tie"}, 
    {"numFilme": 679, "nomePT": "Picardias Estudantis", "nomeOriginal": "Fast Times at Ridgemont High"}, 
    {"numFilme": 680, "nomePT": "E.T.:  O Extraterrestre", "nomeOriginal": "E.T.:  The Extra-Terrestrial"}, 
    {"numFilme": 681, "nomePT": "O Enigma de Outro Mundo", "nomeOriginal": "The Thing"}, 
    {"numFilme": 682, "nomePT": "Poltergeist"}, 
    {"numFilme": 683, "nomePT": "Blade Runner, O Caçador de Andróides", "nomeOriginal": "Blade Runner"}, 
    {"numFilme": 684, "nomePT": "Uma Noite Alucinante:  A Morte do Demônio", "nomeOriginal": "The Evil Dead"}, 
    {"numFilme": 685, "nomePT": "Tootsie"}, 
    {"numFilme": 686, "nomePT": "Yol"}, 
    {"numFilme": 687, "nomePT": "Quando os Jovens se Tornam Adultos", "nomeOriginal": "Diner"}, 
    {"numFilme": 688, "nomePT": "Fitzcarraldo"}, 
    {"numFilme": 689, "nomePT": "Gandhi"}, 
    {"numFilme": 690, "nomePT": "A Noite de São Lourenço", "nomeOriginal": "La Notte Di San Lorenzo"}, 
    {"numFilme": 691, "nomePT": "Uma Questão de Silêncio", "nomeOriginal": "De Stilte Rond Christine M."}, 
    {"numFilme": 692, "nomePT": "Fanny & Alexander", "nomeOriginal": "Fanny Och Alexander"}, 
    {"numFilme": 693, "nomePT": "Uma História de Natal", "nomeOriginal": "A Christmas Story"}, 
    {"numFilme": 694, "nomePT": "El Norte"}, 
    {"numFilme": 695, "nomePT": "Videodrome:  A Síndrome do Vídeo", "nomeOriginal": "Videodrome"}, 
    {"numFilme": 696, "nomePT": "Guerra nas Estrelas:  Episódio VI - O Retorno de Jedi", "nomeOriginal": "Star Wars:  Episode VI - Return of the Jedi"}, 
    {"numFilme": 697, "nomePT": "O Reencontro", "nomeOriginal": "The Big Chill"}, 
    {"numFilme": 698, "nomePT": "Sans Soleil"}, 
    {"numFilme": 699, "nomePT": "O Último Combate", "nomeOriginal": "Le Dernier Combat"}, 
    {"numFilme": 700, "nomePT": "O Dinheiro", "nomeOriginal": "L’Argent"}, 
    {"numFilme": 701, "nomePT": "UTU"}, 
    {"numFilme": 702, "nomePT": "Laços de Ternura", "nomeOriginal": "Terms of Endearment"}, 
    {"numFilme": 703, "nomePT": "O Quarto Homem", "nomeOriginal": "De Vierde Man"}, 
    {"numFilme": 704, "nomePT": "The King of Comedy"}, 
    {"numFilme": 705, "nomePT": "The Right Stuff"}, 
    {"numFilme": 706, "nomePT": "Koyaanisqatsi"}, 
    {"numFilme": 707, "nomePT": "Once Upon a Time in America"}, 
    {"numFilme": 708, "nomePT": "Scarface"}, 
    {"numFilme": 709, "nomePT": "The Ballad of Narayama"}, 
    {"numFilme": 710, "nomePT": "Amadeus"}, 
    {"numFilme": 711, "nomePT": "The Terminator"}, 
    {"numFilme": 712, "nomePT": "Paris, Texas"}, 
    {"numFilme": 713, "nomePT": "A Nightmare on Elm Street"}, 
    {"numFilme": 714, "nomePT": "This Is Spinal Tap"}, 
    {"numFilme": 715, "nomePT": "Beverly Hills Cop"}, 
    {"numFilme": 716, "nomePT": "Ghostbusters"}, 
    {"numFilme": 717, "nomePT": "A Passage to India"}, 
    {"numFilme": 718, "nomePT": "Stranger Than Paradise"}, 
    {"numFilme": 719, "nomePT": "The Killing Fields"}, 
    {"numFilme": 720, "nomePT": "The Natural"}, 
    {"numFilme": 721, "nomePT": "The Breakfast Club"}, 
    {"numFilme": 722, "nomePT": "Ran"}, 
    {"numFilme": 723, "nomePT": "Come and See"}, 
    {"numFilme": 724, "nomePT": "The Official Story"}, 
    {"numFilme": 725, "nomePT": "Out of Africa"}, 
    {"numFilme": 726, "nomePT": "The Purple Rose of Cairo"}, 
    {"numFilme": 727, "nomePT": "Back to the Future"}, 
    {"numFilme": 728, "nomePT": "The Time to Live and the Time to Die"}, 
    {"numFilme": 729, "nomePT": "Brazil"}, 
    {"numFilme": 730, "nomePT": "Kiss of the Spider Woman"}, 
    {"numFilme": 731, "nomePT": "The Quiet Earth"}, 
    {"numFilme": 732, "nomePT": "Mishima:  A Life in Four Chapters"}, 
    {"numFilme": 733, "nomePT": "Prizzi’s Honor"}, 
    {"numFilme": 734, "nomePT": "Vagabond"}, 
    {"numFilme": 735, "nomePT": "Shoah"}, 
    {"numFilme": 736, "nomePT": "The Color Purple"}, 
    {"numFilme": 737, "nomePT": "Manhunter"}, 
    {"numFilme": 738, "nomePT": "Stand By Me"}, 
    {"numFilme": 739, "nomePT": "Blue Velvet"}, 
    {"numFilme": 740, "nomePT": "Hannah and Her Sisters"}, 
    {"numFilme": 741, "nomePT": "She’s Gotta Have It"}, 
    {"numFilme": 742, "nomePT": "The Decline of the American Empire"}, 
    {"numFilme": 743, "nomePT": "The Fly"}, 
    {"numFilme": 744, "nomePT": "Aliens"}, 
    {"numFilme": 745, "nomePT": "Ferris Bueller’s Day Off"}, 
    {"numFilme": 746, "nomePT": "Down by Law"}, 
    {"numFilme": 747, "nomePT": "A Room with a View"}, 
    {"numFilme": 748, "nomePT": "Children of a Lesser God"}, 
    {"numFilme": 749, "nomePT": "Platoon"}, 
    {"numFilme": 750, "nomePT": "Caravaggio"}, 
    {"numFilme": 751, "nomePT": "Tampopo"}, 
    {"numFilme": 752, "nomePT": "Peking Opera Blues"}, 
    {"numFilme": 753, "nomePT": "Salvador"}, 
    {"numFilme": 754, "nomePT": "Top Gun"}, 
    {"numFilme": 755, "nomePT": "Sherman’s March"}, 
    {"numFilme": 756, "nomePT": "The Horse Thief"}, 
    {"numFilme": 757, "nomePT": "Brightness"}, 
    {"numFilme": 758, "nomePT": "Wings of Desire"}, 
    {"numFilme": 759, "nomePT": "Project A, Part II"}, 
    {"numFilme": 760, "nomePT": "Babette’s Feast"}, 
    {"numFilme": 761, "nomePT": "Raising Arizona"}, 
    {"numFilme": 762, "nomePT": "Full Metal Jacket"}, 
    {"numFilme": 763, "nomePT": "Withnail and I"}, 
    {"numFilme": 764, "nomePT": "Good Morning, Vietnam"}, 
    {"numFilme": 765, "nomePT": "Goodbye Children"}, 
    {"numFilme": 766, "nomePT": "Broadcast News"}, 
    {"numFilme": 767, "nomePT": "Housekeeping"}, 
    {"numFilme": 768, "nomePT": "The Princess Bride"}, 
    {"numFilme": 769, "nomePT": "Moonstruck"}, 
    {"numFilme": 770, "nomePT": "The Untouchables"}, 
    {"numFilme": 771, "nomePT": "Red Sorghum"}, 
    {"numFilme": 772, "nomePT": "The Dead"}, 
    {"numFilme": 773, "nomePT": "Fatal Attraction"}, 
    {"numFilme": 774, "nomePT": "A Chinese Ghost Story"}, 
    {"numFilme": 775, "nomePT": "Women on the Verge of a Nervous Breakdown"}, 
    {"numFilme": 776, "nomePT": "The Vanishing"}, 
    {"numFilme": 777, "nomePT": "Bull Durham"}, 
    {"numFilme": 778, "nomePT": "Ariel"}, 
    {"numFilme": 779, "nomePT": "The Thin Blue Line"}, 
    {"numFilme": 780, "nomePT": "Akira"}, 
    {"numFilme": 781, "nomePT": "Cinema Paradiso"}, 
    {"numFilme": 782, "nomePT": "Hotel Terminus:  The Life and Times of Klaus Barbie"}, 
    {"numFilme": 783, "nomePT": "A Fish Called Wanda"}, 
    {"numFilme": 784, "nomePT": "The Naked Gun"}, 
    {"numFilme": 785, "nomePT": "Big"}, 
    {"numFilme": 786, "nomePT": "Dangerous Liaisons"}, 
    {"numFilme": 787, "nomePT": "Grave of the Fireflies"}, 
    {"numFilme": 788, "nomePT": "Landscape in the Mist"}, 
    {"numFilme": 789, "nomePT": "The Decalogue"}, 
    {"numFilme": 790, "nomePT": "Die Hard"}, 
    {"numFilme": 791, "nomePT": "A Tale of the Wind"}, 
    {"numFilme": 792, "nomePT": "Who Framed Roger Rabbit"}, 
    {"numFilme": 793, "nomePT": "Rain Man"}, 
    {"numFilme": 794, "nomePT": "The Story of Women"}, 
    {"numFilme": 795, "nomePT": "Drowning By Numbers"}, 
    {"numFilme": 796, "nomePT": "Alice"}, 
    {"numFilme": 797, "nomePT": "Batman"}, 
    {"numFilme": 798, "nomePT": "When Harry Met Sally"}, 
    {"numFilme": 799, "nomePT": "Crimes and Misdemeanors"}, 
    {"numFilme": 800, "nomePT": "The Cook, the Thief, His Wife and Her Lover"}, 
    {"numFilme": 801, "nomePT": "Drugstore Cowboy"}, 
    {"numFilme": 802, "nomePT": "My Left Foot"}, 
    {"numFilme": 803, "nomePT": "The Killer"}, 
    {"numFilme": 804, "nomePT": "Do the Right Thing"}, 
    {"numFilme": 805, "nomePT": "Roger & Me"}, 
    {"numFilme": 806, "nomePT": "Glory"}, 
    {"numFilme": 807, "nomePT": "The Asthenic Syndrome"}, 
    {"numFilme": 808, "nomePT": "Sex, Lies and Videotape"}, 
    {"numFilme": 809, "nomePT": "Say Anything"}, 
    {"numFilme": 810, "nomePT": "The Unbelievable Truth"}, 
    {"numFilme": 811, "nomePT": "A City of Sadness"}, 
    {"numFilme": 812, "nomePT": "No Fear, No Die"}, 
    {"numFilme": 813, "nomePT": "Reversal of Fortune"}, 
    {"numFilme": 814, "nomePT": "Goodfellas"}, 
    {"numFilme": 815, "nomePT": "Jacob’s Ladder"}, 
    {"numFilme": 816, "nomePT": "King of New York"}, 
    {"numFilme": 817, "nomePT": "Dances with Wolves"}, 
    {"numFilme": 818, "nomePT": "Europa Europa"}, 
    {"numFilme": 819, "nomePT": "Pretty Woman"}, 
    {"numFilme": 820, "nomePT": "Archangel"}, 
    {"numFilme": 821, "nomePT": "Trust"}, 
    {"numFilme": 822, "nomePT": "Close-Up"}, 
    {"numFilme": 823, "nomePT": "Edward Scissorhands"}, 
    {"numFilme": 824, "nomePT": "Henry:  Portrait of a Serial Killer"}, 
    {"numFilme": 825, "nomePT": "Total Recall"}, 
    {"numFilme": 826, "nomePT": "Once Upon a Time in China"}, 
    {"numFilme": 827, "nomePT": "Boyz ‘n the Hood"}, 
    {"numFilme": 828, "nomePT": "Raise the Red Lantern"}, 
    {"numFilme": 829, "nomePT": "Delicatessen"}, 
    {"numFilme": 830, "nomePT": "A Brighter Summer Day"}, 
    {"numFilme": 831, "nomePT": "Naked Lunch"}, 
    {"numFilme": 832, "nomePT": "The Beautiful Troublemaker"}, 
    {"numFilme": 833, "nomePT": "The Rapture"}, 
    {"numFilme": 834, "nomePT": "My Own Private Idaho"}, 
    {"numFilme": 835, "nomePT": "Thelma & Louise"}, 
    {"numFilme": 836, "nomePT": "Terminator 2:  Judgment Day"}, 
    {"numFilme": 837, "nomePT": "The Silence of the Lambs"}, 
    {"numFilme": 838, "nomePT": "JFK"}, 
    {"numFilme": 839, "nomePT": "Slacker"}, 
    {"numFilme": 840, "nomePT": "Tongues Untied"}, 
    {"numFilme": 841, "nomePT": "Hearts of Darkness:  A Filmmaker’s Apocalypse"}, 
    {"numFilme": 842, "nomePT": "The Double Life of Veronique"}, 
    {"numFilme": 843, "nomePT": "Strictly Ballroom"}, 
    {"numFilme": 844, "nomePT": "The Player"}, 
    {"numFilme": 845, "nomePT": "Reservoir Dogs"}, 
    {"numFilme": 846, "nomePT": "Romper Stomper"}, 
    {"numFilme": 847, "nomePT": "Glengarry Glen Ross"}, 
    {"numFilme": 848, "nomePT": "Unforgiven"}, 
    {"numFilme": 849, "nomePT": "Aileen Wuornos:  The Selling of a Serial Killer"}, 
    {"numFilme": 850, "nomePT": "The actress"}, 
    {"numFilme": 851, "nomePT": "A Tale of Winter"}, 
    {"numFilme": 852, "nomePT": "The Actress"}, 
    {"numFilme": 853, "nomePT": "Man Bites Dog"}, 
    {"numFilme": 854, "nomePT": "The Crying Game"}, 
    {"numFilme": 855, "nomePT": "Farewell My Concubine"}, 
    {"numFilme": 856, "nomePT": "Groundhog Day"}, 
    {"numFilme": 857, "nomePT": "Thirty Two Films about Glenn Gould"}, 
    {"numFilme": 858, "nomePT": "Short Cuts"}, 
    {"numFilme": 859, "nomePT": "Philadelphia"}, 
    {"numFilme": 860, "nomePT": "The Puppetmaster"}, 
    {"numFilme": 861, "nomePT": "Jurassic Park"}, 
    {"numFilme": 862, "nomePT": "Three Colors:  Blue"}, 
    {"numFilme": 863, "nomePT": "The Piano"}, 
    {"numFilme": 864, "nomePT": "The Blue Kite"}, 
    {"numFilme": 865, "nomePT": "The Wedding Banquet"}, 
    {"numFilme": 866, "nomePT": "Schindler’s List"}, 
    {"numFilme": 867, "nomePT": "The Adventures of Priscilla, Queen of the Desert"}, 
    {"numFilme": 868, "nomePT": "Three Colors:  Red"}, 
    {"numFilme": 869, "nomePT": "Hoop Dreams"}, 
    {"numFilme": 870, "nomePT": "Forrest Gump"}, 
    {"numFilme": 871, "nomePT": "The Lion King"}, 
    {"numFilme": 872, "nomePT": "Clerks"}, 
    {"numFilme": 873, "nomePT": "Four Weddings and a Funeral"}, 
    {"numFilme": 874, "nomePT": "Natural Born Killers"}, 
    {"numFilme": 875, "nomePT": "The Last Seduction"}, 
    {"numFilme": 876, "nomePT": "Pulp Fiction"}, 
    {"numFilme": 877, "nomePT": "The Shawshank Redemption"}, 
    {"numFilme": 878, "nomePT": "The Wild Reeds"}, 
    {"numFilme": 879, "nomePT": "Chungking Express"}, 
    {"numFilme": 880, "nomePT": "Crumb"}, 
    {"numFilme": 881, "nomePT": "Satantango"}, 
    {"numFilme": 882, "nomePT": "Through the Olive Trees"}, 
    {"numFilme": 883, "nomePT": "Heavenly Creatures"}, 
    {"numFilme": 884, "nomePT": "Riget"}, 
    {"numFilme": 885, "nomePT": "Dear Diary"}, 
    {"numFilme": 886, "nomePT": "Muriel’s Wedding"}, 
    {"numFilme": 887, "nomePT": "The Kingdom"}, 
    {"numFilme": 888, "nomePT": "Babe"}, 
    {"numFilme": 889, "nomePT": "Braveheart"}, 
    {"numFilme": 890, "nomePT": "Safe"}, 
    {"numFilme": 891, "nomePT": "Toy Story"}, 
    {"numFilme": 892, "nomePT": "Casino"}, 
    {"numFilme": 893, "nomePT": "Heat"}, 
    {"numFilme": 894, "nomePT": "Zero Kelvin"}, 
    {"numFilme": 895, "nomePT": "Clueless"}, 
    {"numFilme": 896, "nomePT": "Smoke"}, 
    {"numFilme": 897, "nomePT": "The White Balloon"}, 
    {"numFilme": 898, "nomePT": "Se7en"}, 
    {"numFilme": 899, "nomePT": "Underground"}, 
    {"numFilme": 900, "nomePT": "The Brave Heart Will Take the Bride"}, 
    {"numFilme": 901, "nomePT": "Cyclo"}, 
    {"numFilme": 902, "nomePT": "The Usual Suspects"}, 
    {"numFilme": 903, "nomePT": "Homem Morto", "nomeOriginal": "Dead Man"}, 
    {"numFilme": 904, "nomePT": "Fargo"}, 
    {"numFilme": 905, "nomePT": "Três Vidas E Uma Só Morte", "nomeOriginal": "Trois Vies & Une Seule Mort"}, 
    {"numFilme": 906, "nomePT": "Shine - Brilhante", "nomeOriginal": "Shine"}, 
    {"numFilme": 907, "nomePT": "Ondas Do Destino", "nomeOriginal": "Breaking the Waves"}, 
    {"numFilme": 908, "nomePT": "Independence Day"}, 
    {"numFilme": 909, "nomePT": "Segredos E Mentiras", "nomeOriginal": "Secrets and Lies"}, 
    {"numFilme": 910, "nomePT": "Gabbeh"}, 
    {"numFilme": 911, "nomePT": "Lone Star - A Estrela Solitária", "nomeOriginal": "Lone Star"}, 
    {"numFilme": 912, "nomePT": "Trainspotting"}, 
    {"numFilme": 913, "nomePT": "Pânico", "nomeOriginal": "Scream"}, 
    {"numFilme": 914, "nomePT": "O Paciente Inglês", "nomeOriginal": "The English Patient"}, 
    {"numFilme": 915, "nomePT": "Felizes Juntos", "nomeOriginal": "Cheun Gwong Tsa Sit"}, 
    {"numFilme": 916, "nomePT": "Princesa Mononoke", "nomeOriginal": "Mononoke Hime"}, 
    {"numFilme": 917, "nomePT": "Los Angeles - Cidade Proibida", "nomeOriginal": "L.A. Confidential"}, 
    {"numFilme": 918, "nomePT": "Nó Na Garganta", "nomeOriginal": "The Butcher Boy"}, 
    {"numFilme": 919, "nomePT": "Tempestade De Gelo", "nomeOriginal": "The Ice Storm"}, 
    {"numFilme": 920, "nomePT": "O Doce Amanhã", "nomeOriginal": "The Sweet Hereafter"}, 
    {"numFilme": 921, "nomePT": "Boogie Nights"}, 
    {"numFilme": 922, "nomePT": "Gosto De Cereja", "nomeOriginal": "Ta'm E Guillas"}, 
    {"numFilme": 923, "nomePT": "Jogos Perigosos", "nomeOriginal": "Funny Games"}, 
    {"numFilme": 924, "nomePT": "Titanic"}, 
    {"numFilme": 925, "nomePT": "Abre Los Ojos"}, 
    {"numFilme": 926, "nomePT": "Festa De Família", "nomeOriginal": "Festen"}, 
    {"numFilme": 927, "nomePT": "O Resgate Do Soldado Ryan", "nomeOriginal": "Saving Private Ryan"}, 
    {"numFilme": 928, "nomePT": "Buffalo '66"}, 
    {"numFilme": 929, "nomePT": "Três É Demais", "nomeOriginal": "Rushmore"}, 
    {"numFilme": 930, "nomePT": "Corra Lola Corra", "nomeOriginal": "Lola Rennt"}, 
    {"numFilme": 931, "nomePT": "Felicidade", "nomeOriginal": "Happiness"}, 
    {"numFilme": 932, "nomePT": "Pi"}, 
    {"numFilme": 933, "nomePT": "Quem Vai Ficar Com Mary?", "nomeOriginal": "There’s Something About Mary"}, 
    {"numFilme": 934, "nomePT": "Central Do Brasil"}, 
    {"numFilme": 935, "nomePT": "Além Da Linha Vermelha", "nomeOriginal": "The Thin Red Line"}, 
    {"numFilme": 936, "nomePT": "Três Reis", "nomeOriginal": "Three Kings"}, 
    {"numFilme": 937, "nomePT": "Magnolia"}, 
    {"numFilme": 938, "nomePT": "Clube Da Luta", "nomeOriginal": "Fight Club"}, 
    {"numFilme": 939, "nomePT": "Audition"}, 
    {"numFilme": 940, "nomePT": "A Bruxa De Blair", "nomeOriginal": "The Blair Witch Project"}, 
    {"numFilme": 941, "nomePT": "Tudo Sobre Minha Mãe", "nomeOriginal": "Todo Sobre Mi Madre"}, 
    {"numFilme": 942, "nomePT": "Beau Travail"}, 
    {"numFilme": 943, "nomePT": "Quero Ser John Malkovich", "nomeOriginal": "Being John Malkovich"}, 
    {"numFilme": 944, "nomePT": "Beleza Americana", "nomeOriginal": "American Beauty"}, 
    {"numFilme": 945, "nomePT": "Matrix", "nomeOriginal": "The Matrix"}, 
    {"numFilme": 946, "nomePT": "O Sexto Sentido", "nomeOriginal": "The Sixth Sense"}, 
    {"numFilme": 947, "nomePT": "Os Catadores E Eu", "nomeOriginal": "Les Glaneurs Et La Glaneuse"}, 
    {"numFilme": 948, "nomePT": "Gladiador", "nomeOriginal": "Gladiator"}, 
    {"numFilme": 949, "nomePT": "Amor Á Flor Da Pele", "nomeOriginal": "Dut Yeung Nin Wa"}, 
    {"numFilme": 950, "nomePT": "O Dia Do Perdão", "nomeOriginal": "Kippur"}, 
    {"numFilme": 951, "nomePT": "As Coisas Simples Da Vida", "nomeOriginal": "Yi Yi"}, 
    {"numFilme": 952, "nomePT": "Réquiem Para Um Sonho", "nomeOriginal": "Requiem For a Dream"}, 
    {"numFilme": 953, "nomePT": "Amores Brutos", "nomeOriginal": "Amores Perros"}, 
    {"numFilme": 954, "nomePT": "Entrando Numa Fria", "nomeOriginal": "Meet the Parents"}, 
    {"numFilme": 955, "nomePT": "Traffic"}, 
    {"numFilme": 956, "nomePT": "O Tigre E O Dragão", "nomeOriginal": "Wo Hu Cang Long"}, 
    {"numFilme": 957, "nomePT": "Amnésia", "nomeOriginal": "Memento"}, 
    {"numFilme": 958, "nomePT": "O Fabuloso Destino De Amélie Poulain", "nomeOriginal": "Le Fabuleux Destin D'Amélie Poulain"}, 
    {"numFilme": 959, "nomePT": "Moulin Rouge!"}, 
    {"numFilme": 960, "nomePT": "A Caminho De Kandahar", "nomeOriginal": "Kandahar"}, 
    {"numFilme": 961, "nomePT": "Terra De Ninguém", "nomeOriginal": "No Man’s Land"}, 
    {"numFilme": 962, "nomePT": "A Viagem De Chihiro", "nomeOriginal": "Sen To Chihiro No Kamikakushi"}, 
    {"numFilme": 963, "nomePT": "Os Excêntricos Tenenbaums", "nomeOriginal": "The Royal Tenenbaums"}, 
    {"numFilme": 964, "nomePT": "O Senhor Dos Anéis", "nomeOriginal": "The Lord Of The Rings"}, 
    {"numFilme": 965, "nomePT": "Lantana"}, 
    {"numFilme": 966, "nomePT": "Longínquo", "nomeOriginal": "Uzak"}, 
    {"numFilme": 967, "nomePT": "O Pianista", "nomeOriginal": "The Pianist"}, 
    {"numFilme": 968, "nomePT": "Geração Roubada", "nomeOriginal": "Rabbit-Proof Fence"}, 
    {"numFilme": 969, "nomePT": "Cidade De Deus"}, 
    {"numFilme": 970, "nomePT": "Fale Com Ela", "nomeOriginal": "Hable Con Ella"}, 
    {"numFilme": 971, "nomePT": "Irreversível", "nomeOriginal": "Irreversible"}, 
    {"numFilme": 972, "nomePT": "A Melhor Juventude", "nomeOriginal": "La Meglio Gioventú"}, 
    {"numFilme": 973, "nomePT": "Oldboy"}, 
    {"numFilme": 974, "nomePT": "Kill Bill :  Volume Um", "nomeOriginal": "Kill Bill:  Volume One"}, 
    {"numFilme": 975, "nomePT": "Adeus, Lênin!", "nomeOriginal": "Good Bye Lenin!"}, 
    {"numFilme": 976, "nomePT": "Contra A Parede", "nomeOriginal": "Gegen Die Wand"}, 
    {"numFilme": 977, "nomePT": "Ferro 3", "nomeOriginal": "Bin-Jip"}, 
    {"numFilme": 978, "nomePT": "A Paixão De Cristo", "nomeOriginal": "The Passion Of The Christ"}, 
    {"numFilme": 979, "nomePT": "Crash"}, 
    {"numFilme": 980, "nomePT": "A Queda - As Últimas Horas De Hitler", "nomeOriginal": "Der Untergang"}, 
    {"numFilme": 981, "nomePT": "Entre Umas E Outras", "nomeOriginal": "Sideways"}, 
    {"numFilme": 982, "nomePT": "Fahrenheit 9/11"}, 
    {"numFilme": 983, "nomePT": "um Herói do Nosso Tempo", "nomeOriginal": "Va, Vis Et Deviens"}, 
    {"numFilme": 984, "nomePT": "Paradise Now"}, 
    {"numFilme": 985, "nomePT": "O Segredo de Brokeback Mountain", "nomeOriginal": "Brokeback Mountain"}, 
    {"numFilme": 986, "nomePT": "Infância Roubada", "nomeOriginal": "Tsotsi"}, 
    {"numFilme": 987, "nomePT": "Pequena Miss Sunshine", "nomeOriginal": "Little Miss Sunshine"}, 
    {"numFilme": 988, "nomePT": "Apocalypto"}, 
    {"numFilme": 989, "nomePT": "Os Infiltrados", "nomeOriginal": "The Departed"}, 
    {"numFilme": 990, "nomePT": "O Labirinto do Fauno", "nomeOriginal": "Pan’s Ladyrinth"}, 
    {"numFilme": 991, "nomePT": "Borat"}, 
    {"numFilme": 992, "nomePT": "A Vida Dos Outros", "nomeOriginal": "Das Leben Der Anderen"}, 
    {"numFilme": 993, "nomePT": "Apenas Uma Vez", "nomeOriginal": "Once"}, 
    {"numFilme": 994, "nomePT": "A Rainha", "nomeOriginal": "The Queen"}, 
    {"numFilme": 995, "nomePT": "O Hospedeiro", "nomeOriginal": "The Host"}, 
    {"numFilme": 996, "nomePT": "O Escafandro e a Borboleta", "nomeOriginal": "The Diving Bell and the Butterfly"}, 
    {"numFilme": 997, "nomePT": "Piaf - Um Hino Ao Amor", "nomeOriginal": "La Vie en Rose"}, 
    {"numFilme": 998, "nomePT": "Onde Os Fracos Não Tem Vez", "nomeOriginal": "No Country for Old Men"}, 
    {"numFilme": 999, "nomePT": "Na Natureza Selvagem", "nomeOriginal": "Into The Wild"}, 
    {"numFilme": 1000, "nomePT": "Sangue Negro", "nomeOriginal": "There Will Be Blood"}, 
    {"numFilme": 1001, "nomePT": "Desejo e Reparação", "nomeOriginal": "Atonement"}
]